@startuml MII KDS Erweiterungsmodul Onkologie

skinparam dpi 52
object Patient {
* birthDate = 1956-03-14
* name.family = "Musterperson"
* name.given = "Kim"
}

object Diagnose_Primaertumor #FFFF66 {
* recordedDate = 2021-06-10
* subject = Reference(PatientKimMusterperson)
* clinicalStatus = #active //
* verificationStatus.coding[primaertumorDiagnosesicherung].code = #2 "klinische Diagnostik" 
* code.coding  = $ICD10GM#C48.2 "Bösartige Neubildung des Retroperitoneums und Peritoneums - Peritoneum, nicht näher bezeichnet "
* bodySite = $ICDO3#C56.9 "Ovar"
}
Patient -down-> Diagnose_Primaertumor

object DiagnosticProcedure_1 {
* subject = Reference(PatientKimMusterperson)
* reasonReference = Reference(Primaerdiagnose)    
* status = #completed
* code.coding = $OPS#3-225 "CT des Abdomens mit KM"
* code.coding.version = "OPS 2024"
* performedDateTime = 2021-06-10
}

object DiagnosticProcedure_2 {
* subject = Reference(PatientKimMusterperson)
* reasonReference = Reference(Primaerdiagnose)
* status = #completed
* code.coding = $OPS#1-853.2 "Aszitespunktion"
* performedDateTime = 2021-06-15
}

object DiagnosticProcedure_3 {
* subject = Reference(PatientKimMusterperson)
* reasonReference = Reference(Primaerdiagnose)    
* status = #completed
* code.coding = $OPS#3-222 "CT Thorax"
* performedDateTime = 2021-06-22
}



DiagnosticProcedure_1 -left--> Diagnose_Primaertumor
DiagnosticProcedure_2 -left---> Diagnose_Primaertumor
DiagnosticProcedure_3 -left----> Diagnose_Primaertumor


object Tumorboard_1 #CCCCFF {
* addresses = Reference(Primaerdiagnose)
* subject = Reference(PatientKimMusterperson)
* status = #completed
* intent = #plan
* category.coding = $mii-cs-onko-therapieplanung-typ#praeth "Prätherapeutische Tumorkonferenz" 
* created = 2021-06-25
* activity[0].detail.code = $mii-cs-onko-therapie-typ#CH "Chemotherapie"
* activity[0].detail.status = #completed // Es wurden nur 3 Zyklen geplant, die alle durchgeführt wurden
* activity[0].detail.statusReason = $mii-cs-onko-therapieabweichung#N
* activity[1].detail.code = $mii-cs-onko-therapie-typ#OP
* activity[1].detail.status = #completed
* activity[1].detail.statusReason = $mii-cs-onko-therapieabweichung#N
}
object SystemicTherapy_1 #AAAAFF {
* subject = Reference(PatientKimMusterperson)
* reasonReference = Reference(Primaerdiagnose)    
* status = #completed
* code.coding = $OPS#8-54 "Chemotherapie " // bei Bedarf spezifischer? 
* extension[Intention].valueCodeableConcept = $mii-cs-onko-intention#K // impliziert 
* extension[Stellung].valueCodeableConcept = $mii-cs-onko-systemische-therapie-stellung#N "neo"
* performedPeriod.start = 2021-07-05
* performedPeriod.end = 2021-09-05
* basedOn = Reference(Tumorkonferenz-1)
}

object SystemicTherapyMedication_1 #FFCCFF {
* subject = Reference(PatientKimMusterperson)
* reasonReference = Reference(Primaerdiagnose)    
* status = #completed
* effectivePeriod.start = 2021-07-05  
* effectivePeriod.end = 2021-09-05
* medicationCodeableConcept.coding[atcClassDe][0] = $ATC_DE#L01CD01 "Paclitaxel"
* medicationCodeableConcept.coding[atcClassDe][1] = $ATC_DE#L01XA02 "Carboplatin"
* partOf = Reference(SystemicTherapy_1)
* note.text = "CarboTax"
}

Diagnose_Primaertumor -down-> Tumorboard_1
SystemicTherapy_1 -left--> Tumorboard_1
SystemicTherapyMedication_1 -left-> SystemicTherapy_1 


object SystemicTherapyMedicationAdministration_1_2_3 {
* Detailinformation zu Dosis und Applikation
}
SystemicTherapyMedicationAdministration_1_2_3 -right-> SystemicTherapyMedication_1


object Verlauf_21_09_15 #22FF22 {
* subject = Reference(PatientKimMusterperson)
* focus = Reference(Primaerdiagnose)
* status = #final
* effectiveDateTime = 2021-09-15
* code.coding = $mii-cs-onko-verlauf-gesamtbeurteilung#P "Progression"
* component[Tumor_Verlauf].code.coding = $SCT#277062004 "Status des Residualtumors"
* component[Tumor_Verlauf].valueCodeableConcept = $mii-cs-onko-verlauf-primaertumor#P "Tumorreste (Residualtumor) Progress"
* component[Lymphknoten_Verlauf].code.coding =  $SCT#277060007 "Status der lymphatischen Tumorinvasion"
* component[Lymphknoten_Verlauf].valueCodeableConcept = $mii-cs-onko-verlauf-lymphknoten#R "neu aufgetretenes Lymphknotenrezidiv" 
* component[Fernmetastasen_Verlauf].code.coding = $SCT#260874000 "Status der Metastasen"
* component[Fernmetastasen_Verlauf].valueCodeableConcept = $mii-cs-onko-verlauf-fernmetastasen#K "Keine Änderung"
}
Tumorboard_1 -down-> Verlauf_21_09_15 

object Tumorboard_2 #CCCCFF {
* subject = Reference(PatientKimMusterperson)
* addresses = Reference(Primaerdiagnose)
* status = #completed
* intent = #plan
* category.coding = $mii-cs-onko-therapieplanung-typ#praeth "Prätherapeutische Tumorkonferenz" 
* created = 2021-09-16
* addresses = Reference(OncologicExamplePatientPrimaryDiagnosis2)
* activity[0].detail.code = $mii-cs-onko-therapie-typ#OP
* activity[0].detail.status = #completed
* activity[0].detail.statusReason = $mii-cs-onko-therapieabweichung#N
}
Verlauf_21_09_15  -down-> Tumorboard_2

object SurgicalProcedure_1 #AAAAFF {
* status = #completed
* reasonReference = Reference(Primaerdiagnose)    
* subject = Reference(PatientKimMusterperson)
* code.coding[0] = $OPS#5-547.0 "Resektion von Gewebe ohne sichere Organzuordnung - intraperitoneal" // alternativ 5-590.8 Resektion von Gewebe ohne sichere Organzuordnung
* code.coding[1] = $OPS#5-683 "Hysterektomie"
* code.coding[2] = $OPS#5-661 "bilaterale Adnexektomie / Salpingektomie"
* code.coding[3] = $OPS#5-501 "atypische Lebersegmentresektion"
* performedDateTime = 2021-09-30
* outcome = $mii-cs-onko-residualstatus#R0
}
 Tumorboard_2 <-right-- "basedOn" SurgicalProcedure_1 

object TNM_Klassifikation #22FF22 {
* focus = Reference(Primaerdiagnose)
* subject = Reference(PatientKimMusterperson)
* status = #completed
* code.coding = $SCT#263642008 "Tumor-node-metastasis (TNM) staging classification (attribute)"
* effectiveDateTime = 2021-06-22
* method = #8
* partOf = Reference(OncologicExamplePatientProcedure4)
}
object TNM_T_Kategorie #22FF22 {
* status = #completed
* subject = Reference(PatientKimMusterperson)
* focus = Reference(Primaerdiagnose)
* code.extension[cpPraefix].valueCodeableConcept = $UICC#p
* code.coding =  $SCT#384625004 "pT category (observable entity)"
* effectiveDateTime = 2021-06-22
* method = #8
* partOf = Reference(OncologicExamplePatientProcedure4)
* valueCodeableConcept.coding = $UICC#T3c
}
object TNM_M_Kategorie #22FF22 {
* status = #completed
* subject = Reference(PatientKimMusterperson)
* focus = Reference(Primaerdiagnose)
* code.extension[cpPraefix].valueCodeableConcept = $UICC#p
* code.coding = $SCT#371497001 "pM category (observable entity)"
* effectiveDateTime = 2021-06-22
* method = #8
* partOf = Reference(PatientKimMusterperson-Procedure-4)
* valueCodeableConcept.coding = $UICC#M1b
}

object TNM_y_Symbol #22FF22 {
* status = #completed
* subject = Reference(PatientKimMusterperson)
* focus = Reference(Primaerdiagnose)
* code.coding = $LOINC#101658-3
* effectiveDateTime = 2021-06-22
* method = #8
* partOf = Reference(PatientKimMusterperson-Procedure-4)
* valueCodeableConcept.coding = $SCT#421755005
}
object TNM_Pn_Observation #22FF22 {
* status = #completed
* subject = Reference(PatientKimMusterperson)
* focus = Reference(Primaerdiagnose)
* code.coding = $SCT#371513001
* effectiveDateTime = 2021-06-22
* method = #8
* partOf = Reference(PatientKimMusterperson-Procedure-4)
* valueCodeableConcept.coding = $UICC#Pn0
}

object TNM_L_Observation #22FF22 {
* status = #completed
* subject = Reference(PatientKimMusterperson
* focus = Reference(Primaerdiagnose))
* code.coding = $SCT#395715009
* effectiveDateTime = 2021-06-22
* method = #8
* partOf = Reference(PatientKimMusterperson-Procedure-4)
* valueCodeableConcept.coding = $UICC#L1
}
object TNM_V_Observation #22FF22 {
* status = #completed
* subject = Reference(PatientKimMusterperson)
* focus = Reference(Primaerdiagnose)
* code.coding = $SCT#371493002
* effectiveDateTime = 2021-06-22
* method = #8
* partOf = Reference(PatientKimMusterperson-Procedure-4)
* valueCodeableConcept.coding = $UICC#V0
}

TNM_Klassifikation -left-> SurgicalProcedure_1
TNM_T_Kategorie -up-> TNM_Klassifikation
TNM_M_Kategorie -up-> TNM_Klassifikation
TNM_y_Symbol -up--> TNM_Klassifikation
TNM_Pn_Observation -up--> TNM_Klassifikation
TNM_L_Observation -up--> TNM_Klassifikation
TNM_V_Observation -up--> TNM_Klassifikation 

object FIGO_Observation_2 #22FF22 {
* status = #completed
* subject = Reference(PatientKimMusterperson)
* focus = Reference(Primaerdiagnose)
* code.coding = $SCT#385361009 "International Federation of Gynecology and Obstetrics tumor stage (observable entity)"
* code.text = "FIGO Klassifikation für ovariale Tumore"
* effectiveDateTime = 2021-06-22
* method = $SCT#254386003 "International Federation of Gynecology and Obstetrics ovarian tumor staging system (tumor staging)"
* partOf = Reference(PatientKimMusterperson-Procedure-4)
* valueCodeableConcept.coding.code = #IVB
}
FIGO_Observation_2 -left----->  SurgicalProcedure_1

object Tumorboard_3 #CCCCFF {
* subject = Reference(PatientKimMusterperson)
* addresses = Reference(Primaerdiagnose)
* status = #completed
* intent = #plan
* category.coding = $mii-cs-onko-therapieplanung-typ#postop "Posttherapeutische Tumorkonferenz" 
* created = 2021-10-25
* replaces = Reference(PatientKimMusterperson-Tumorkonferenz-2)
* addresses = Reference(PatientKimMusterperson-PrimaryDiagnosis-2)
* activity[0].detail.code = $mii-cs-onko-therapie-typ#CH
* activity[0].detail.status = #completed // unklar, weil genaue Zyklenanzahl nicht beschrieben ist
* activity[0].detail.statusReason = $mii-cs-onko-therapieabweichung#N
} 
object Pathobericht_1 #88FF88{
* subject = Reference(PatientKimMusterperson)
* status = #complete
* code.coding = $LOINC#60568-3 "Pathological laboratory report"
* conclusion = '"Histologie: Resektat vom 30.09.2021: Neoplasie des Ovars (Z.n. neoadjuvanter Therapie) (ICD-10-C56)
 Ovar o.n.A. (ICD-O-C56.9) Untersuchungsmaterial: Resektat WHO-Typ: Seröses Adenokarzinom (ICD-O M-8441/3) 
 Lokale Tumorausbreitung: Ovartumor links mit einer max. Größe von 2,2 cm und tumorinfiltrierter Kapsel 
 mit Nachweis von Tumorzellen auf der Ovaroberfläche, Anteil vitaler Tumorzellen von ca. 80 %. 
 UICC-Klassifikation (8. Auflage): ypT3c. pM1b (HEP) L1. V0. Pn0 FIGO: IVB"'
}

object Bioprobe_1 #44FFFF {
* subject = Reference(PatientKimMusterperson)
* identifier.value = "12345678"
* collection.collectedDateTime = 2021-09-30 
}
Bioprobe_1 -up->  SurgicalProcedure_1
Pathobericht_1 --up->SurgicalProcedure_1

object Verlauf_21_10_25 #22FF22 {
* subject = Reference(PatientKimMusterperson)
* focus = Reference(Primaerdiagnose)
* status = #final
* effectiveDateTime = 2021-10-25
* code.coding = $mii-cs-onko-verlauf-gesamtbeurteilung#V "Vollremission" // 26 Tage postop, aber sehr unsicher weil Neoadjuvanter progress
* component[Tumor_Verlauf].code.coding = $SCT#277062004 "Status des Residualtumors"
* component[Tumor_Verlauf].valueCodeableConcept = $mii-cs-onko-verlauf-primaertumor#K "kein Tumor nachweisbar"
}
Tumorboard_2 -down-> Verlauf_21_10_25

Verlauf_21_10_25-down->Tumorboard_3 

''Verlauf_21_10_25 <-right---- SurgicalProcedure_1

object Verlauf_22_01_22 #22FF22 {
* subject = Reference(PatientKimMusterperson)
* focus = Reference(Primaerdiagnose)
* status = #final
* effectiveDateTime = 2022-01-22
* code.coding = $mii-cs-onko-verlauf-gesamtbeurteilung#V "Vollremission" 
* component[Tumor_Verlauf].code.coding = $SCT#277062004 "Status des Residualtumors"
* component[Tumor_Verlauf].valueCodeableConcept = $mii-cs-onko-verlauf-primaertumor#T "Tumorreste (Residualtumor)"
* component[Fernmetastasen_Verlauf].code.coding = $SCT#260874000 "Status der Metastasen"
* component[Fernmetastasen_Verlauf].valueCodeableConcept = $mii-cs-onko-verlauf-fernmetastasen#K "Keine Fernmetastasen nachweisbar"
}
Tumorboard_3 -down->Verlauf_22_01_22

object SystemicTherapy_2  #AAAAFF {
* subject = Reference(PatientKimMusterperson)
* reasonReference = Reference(Primaerdiagnose)
* status = #completed
* code.coding = $OPS#8-54 "Chemotherapie " // bei Bedarf spezifischer? 
* extension[Intention].valueCodeableConcept = $mii-cs-onko-intention#K // impliziert 
* extension[Stellung].valueCodeableConcept = $mii-cs-onko-systemische-therapie-stellung#A "adjuvant"
* performedPeriod.start = 2021-11-08
* performedPeriod.end = 2022-01-09
}
SystemicTherapy_2 -up-> Tumorboard_3

object SystemicTherapyMedication_2 #FFCCFF {
* subject = Reference(PatientKimMusterperson)
* reasonReference = Reference(Primaerdiagnose)
* status = #completed
* effectivePeriod.start = 2021-11-08  
* effectivePeriod.end = 2022-01-09
* medicationCodeableConcept.coding[atcClassDe][0] = $ATC_DE#L01BC05 "Gemcitabin"
* medicationCodeableConcept.coding[atcClassDe][1] = $ATC_DE#L01XA02 "Carboplatin"
* partOf = Reference(PatientKimMusterperson-SystemicTherapy-2)
* note.text = "Gem-Carbo"
}
SystemicTherapyMedication_2 -left-> SystemicTherapy_2





object GenetischeVariante_1 #22FF22 {
* subject = Reference(PatientKimMusterperson)
* focus = Reference(Primaerdiagnose)
* status = #final
* note.text = "BRCAwt"
* interpretation = $mii-cs-onko-genetische-variante-auspraegung#W "Wildtyp"
}
GenetischeVariante_1 -up--> Tumorboard_3

object Tumorboard_4 #CCCCFF {
* subject = Reference(PatientKimMusterperson)
* addresses = Reference(Primaerdiagnose)
* status = #active
* intent = #plan
* category.coding = $mii-cs-onko-therapieplanung-typ#postop "postoperativ Tumorkonferenz" 
* created = 2022-01-20
* replaces = Reference(PatientKimMusterperson-Tumorkonferenz-3)
* addresses = Reference(OncologicExamplePatientPrimaryDiagnosis2)
* activity[0].detail.code = $mii-cs-onko-therapie-typ#ZS
* activity[0].detail.status = #active 
* activity[0].detail.statusReason = $mii-cs-onko-therapieabweichung#U "unbekannt"
* description = "Erhaltungstherapie mit Niraparib bei BRCAwt"
}

Verlauf_22_01_22 --down->Tumorboard_4

object SystemicTherapy_3 #AAAAFF {
* subject = Reference(PatientKimMusterperson)
* focus = Reference(Primaerdiagnose)
* status = #active
* code.coding = $OPS#8-54 "Chemotherapie " 
* extension[Intention].valueCodeableConcept = $mii-cs-onko-intention#K 
* extension[Stellung].valueCodeableConcept = $mii-cs-onko-systemische-therapie-stellung#A "adjuvant"
* performedPeriod.start = 2021-11-15
}

object SystemicTherapyMedication_3 #FFCCFF {
* subject = Reference(PatientKimMusterperson)
* reasonReference = Reference(Primaerdiagnose)
* status = #active
* effectivePeriod.start = 2022-01-25  
* medicationCodeableConcept.coding[atcClassDe][0] = $ATC_DE#L01XK02  "Niraparib"
* partOf = Reference(PatientKimMusterperson-SystemicTherapy-3)
* note.text = "Niraparib"
}
SystemicTherapy_3 -left-> Tumorboard_4

SystemicTherapyMedication_3 -left-> SystemicTherapy_3


object Primaerdiagnose_final #FFFF66 {
* recordedDate = 2021-10-25 
* subject = Reference(PatientKimMusterperson)
* clinicalStatus = #remission 
* verificationStatus.coding[primaertumorDiagnosesicherung].code = #7.1 "histologische Untersuchung eines Primärtumors" 
* code.coding[0]  = $ICD10GM#C56   
* code.coding[1]  = $ICDO3#M_8441_3 "Seröses Adenokarzinom" 
* bodySite = $ICDO3#C56.9 "Ovar o.n.A."
}

legend right 
|Color|Type|
|<#FFFF66>|Condition|
|<#CCCCFF>|CarePlan|
|<#AAAAFF>|Procedure|
|<#DDFFDD>|ServiceRequest|
|<#88FF88>|DiagnosticReport|
|<#22FF22>|Observation|
|<#FFCCFF>|Medication|
|<#FF9999>|AdverseEvent|
|<#44FFFF>|Specimen|
endlegend


@enduml