@startuml MII_Onko_06_Histologie

object R4_Observation #22FF22

Map  NrUntersuchteLymphknoten #22FF22 {
    6.7 Anzahl unters. Lymphkn. => Observation.valueQuantity.value
}

R4_Observation <|-down- NrUntersuchteLymphknoten

Map NrBefalleneLymphknoten #22FF22 {
6.8 Anzahl bef. Lymphkn. => Observation.valueQuantity.value
}
R4_Observation <|-down-- NrBefalleneLymphknoten


Map NrUntersuchteSentinelLymphknoten  #22FF22{
6.9 Anzahl unters. Sent.-Lymphkn. => Observation.valueQuantity.value
}

R4_Observation <|-down--- NrUntersuchteSentinelLymphknoten

Map NrBefalleneSentinelLymphknoten  #22FF22{
6.10 Anzahl bef. Sent.-Lymphkn. => Observation.valueQuantity.value
}
R4_Observation <|-down-- NrBefalleneSentinelLymphknoten

Map Onko_Verlaufshistologie #22FF22 {
    06.3 Tumor-Histologiedatum=> Condition.extension[morphology-behaviour-icdo3].valueCodeableConcept.coding[icd-o-3].code
    06.3 Morphologie-Code => Condition.extension[morphology-behaviour-icdo3].valueCodeableConcept.coding[icd-o-3].code
    06.4 Morphologie ICD-O/Blue Book Version => Condition.extension[morphology-behaviour-icdo3].valueCodeableConcept.coding[icd-o-3].version
    06.5 Morphologie-Freitext => Condition.extension[morphology-behaviour-icdo3].valueCodeableConcept.coding[icd-o-3].code
}

R4_Observation <|-down-- Onko_Verlaufshistologie


Map Onko_Grading #22FF22 {
6.6 Grading =>Observation.valueCodeableConcept.coding.code
}
R4_Observation <|-- Onko_Grading

Map Onko_Befund #AAFFAA{
6.11 Befund => DiagnosticReport.conclusion
}

 
object R4_DiagnosticReport #AAFFAA
R4_DiagnosticReport <|-- Onko_Befund 

Map Onko_Specimen #44FFFF {
6.1 Tumor Histologiedatum => Specimen.collection.collectedDateTime
6.2 Histologie-Einsendenummer => Specimen.identifier.value
}

object R4_Specimen #44FFFF
R4_Specimen <|---- Onko_Specimen

legend right 
|Color|Type|
|<#FFFF66>|Condition|
|<#CCCCFF>|CarePlan|
|<#9999FF>|Procedure|
|<#DDFFDD>|ServiceRequest|
|<#AAFFAA>|DiagnosticReport|
|<#22FF22>|Observation|
|<#FFCCFF>|Medication|
|<#FF9999>|AdverseEvent|
|<#44FFFF>|Specimen|
endlegend



@enduml