//skinparam linetype polyline 
//skinparam linetype ortho
@startuml MII_Onko_UML_Relations_v1
skinparam linetype polyline
object Onko_OP [[StructureDefinition-mii-pr-onko-operation.html]] #9999FF
object Onko_Strahlentherapie [[StructureDefinition-mii-pr-onko-strahlentherapie.html]] #9999FF
object Onko_SystemischeTherapie [[StructureDefinition-mii-pr-onko-systemische-therapie.html]] #9999FF
object Therapieplanung_Tumorkonferenz [[StructureDefinition-mii-pr-onko-tumorkonferenz.html]] #CCCCFF
Therapieplanung_Tumorkonferenz <-- Onko_OP: basedOn 
Therapieplanung_Tumorkonferenz <-- Onko_Strahlentherapie: basedOn
Therapieplanung_Tumorkonferenz <-- Onko_SystemischeTherapie: basedOn
rectangle "Medikation" {
    object MedicationStatement [[StructureDefinition-mii-pr-onko-systemische-therapie-medikation.html]] #FFCCFF
}
Onko_SystemischeTherapie <--- MedicationStatement : partOf 
Therapieplanung_Tumorkonferenz <--- MedicationStatement: basedOn
object Diagnose_Primaertumor [[StructureDefinition-mii-pr-onko-diagnose-primaertumor.html]] #FFFF66
object Evidenz_Erstdiagnose [[StructureDefinition-mii-pr-onko-liste-evidenz-erstdiagnose.html]] #EEEEEE
Diagnose_Primaertumor --left--> Evidenz_Erstdiagnose : evidence.detail



rectangle "Onkologie Observations"{
    object Onko_Variante [[StructureDefinition-mii-pr-onko-genetische-variante.html]] #22FF22
    object Fernmetastasen [[StructureDefinition-mii-pr-onko-fernmetastasen.html]] #22FF22
    object TNM_Klassifikation [[StructureDefinition-mii-pr-onko-tnm-klassifikation.html]] #22FF22
    object WeitereKlassifikation [[StructureDefinition-mii-pr-onko-weitere-klassifikationen.html]] #22FF22
    object Lymphknotenuntersuchung [[StructureDefinition-mii-pr-onko-anzahl-untersuchte-lymphknoten.html]] #22FF22
    object HistologieGrading [[StructureDefinition-mii-pr-onko-histologie-icdo3.html]] #22FF22
    object Residualstatus [[StructureDefinition-mii-pr-onko-residualstatus.html]] #22FF22
    object Allgemeiner_Leistungszustand [[StructureDefinition-mii-pr-onko-allgemeiner-leistungszustand-ecog.html]] #22FF22
    object Tod [[StructureDefinition-mii-pr-onko-tod.html]] #22FF22
    object Onko_Befund [[StructureDefinition-mii-pr-onko-befund.html]] #88FF88
}

Diagnose_Primaertumor <--- TNM_Klassifikation: focus
Diagnose_Primaertumor <-right--  Therapieplanung_Tumorkonferenz : addresses
Diagnose_Primaertumor <--- Lymphknotenuntersuchung: focus
Diagnose_Primaertumor <--- HistologieGrading :focus
Diagnose_Primaertumor <--- Onko_Variante :focus
Diagnose_Primaertumor <--- WeitereKlassifikation: focus
Diagnose_Primaertumor <--- Allgemeiner_Leistungszustand :focus
Diagnose_Primaertumor <--- Fernmetastasen :focus

Therapieplanung_Tumorkonferenz <-right-- Onko_Befund  : basedOn

object Verlauf [[StructureDefinition-mii-pr-onko-verlauf.html]] #22FF22
Diagnose_Primaertumor <----  Verlauf : focus
Verlauf ---> Tod: hasMember
Verlauf ---> TNM_Klassifikation:  hasMember
Verlauf --->  Lymphknotenuntersuchung : hasMember
Verlauf --->  HistologieGrading : hasMember
Verlauf ---> Fernmetastasen: hasMember
Verlauf ---> Residualstatus:  hasMember
Verlauf ---> Onko_Variante: hasMember

object Onko_Bioprobe [[StructureDefinition-mii-pr-onko-specimen.html]] #44FFFF
Onko_Bioprobe <-- Onko_Befund : specimen
Onko_Variante ...> Onko_Bioprobe: specimen (0..1)

object AdverseEvent [[StructureDefinition-mii-pr-onko-nebenwirkung-adverse-event.html]] #FF9999
Onko_SystemischeTherapie <--- AdverseEvent: suspectEntity.instance
Onko_Strahlentherapie <--- AdverseEvent: suspectEntity.instance

legend right 
|Color|Type|
|<#FFFF66>|Condition|
|<#CCCCFF>|CarePlan|
|<#9999FF>|Procedure|
|<#DDFFDD>|ServiceRequest|
|<#88FF88>|DiagnosticReport|
|<#22FF22>|Observation|
|<#FFCCFF>|Medication|
|<#FF9999>|AdverseEvent|
|<#44FFFF>|Specimen|
endlegend


@enduml