@startuml MII_Onko_08_TNM
object R4_Observation #22FF22

Map TNM_Klassifikation #22FF22 {
  8.1 TNM Datum  => effectiveDateTime
  8.2 TNM Version =>method
  8.17 UICC Stadium => valueCodeableConcept.coding.code
  TNM-Typ (clinical/pathologic/integrated) => code
}
R4_Observation <|-down- TNM_Klassifikation

object MII_Diagnose #FFFF66
TNM_Klassifikation --> "0..1" MII_Diagnose : focus

Map TNM_Klassifikation_Synthetisiert #22FF22 {
  TNM-Typ (fix, integriert) => code = SCT#399703000
  UICC-Stadium => valueCodeableConcept [1..1]
  TNM-Formel => component[tnmFormel].valueString [0..1]
  Erzeugendes System => device
}
TNM_Klassifikation <|-- TNM_Klassifikation_Synthetisiert
TNM_Klassifikation_Synthetisiert --> "1..*" TNM_Klassifikation : derivedFrom

Map TNM_T #22FF22{
    8.6 TNM c/p-Präfix T => code.extension[cpPraefix].valueCodeableConcept.coding.code
    8.9 TNM T-Kategorie => valueCodeableConcept.coding.code
    8.3 TNM y-Symbol => modifierExtension[yPraefix].valueCodeableConcept.coding.code
    8.4 TNM r-Symbol => modifierExtension[rPraefix].valueCodeableConcept.coding.code
    8.5 TNM a-Symbol => modifierExtension[aPraefix].valueCodeableConcept.coding.code
   }

TNM_Klassifikation o-- TNM_T : hasMember
Map TNM_N #22FF22{
    8.7 TNM c/p-Präfix N => code.extension[cpPraefix].valueCodeableConcept.coding.code
    8.11 TNM N-Kategorie => valueCodeableConcept.coding.code
    ITC-Suffix (i+/i-/mol+/mol-) => value[x].extension[itcSuffix]
    Sentinel-Suffix (sn) => value[x].extension[snSuffix]
    8.3 TNM y-Symbol => modifierExtension[yPraefix].valueCodeableConcept.coding.code
    8.4 TNM r-Symbol => modifierExtension[rPraefix].valueCodeableConcept.coding.code
    8.5 TNM a-Symbol => modifierExtension[aPraefix].valueCodeableConcept.coding.code
   }
TNM_Klassifikation o--- TNM_N : hasMember
Map TNM_M #22FF22{
    8.8 TNM c/p-Präfix M => code.extension[cpPraefix].valueCodeableConcept.coding.code
    8.12 TNM M-Kategorie => valueCodeableConcept.coding.code
    ITC-Suffix (i+/i-/mol+/mol-) => value[x].extension[itcSuffix]
    8.3 TNM y-Symbol => modifierExtension[yPraefix].valueCodeableConcept.coding.code
    8.4 TNM r-Symbol => modifierExtension[rPraefix].valueCodeableConcept.coding.code
    8.5 TNM a-Symbol => modifierExtension[aPraefix].valueCodeableConcept.coding.code
   }
TNM_Klassifikation o---- TNM_M : hasMember
Map TNM_m #22FF22{
    8.10 TNM m-Symbol => valueCodeableConcept.coding.code
}
TNM_Klassifikation o-- TNM_m : hasMember
Map TNM_a #22FF22{
    8.5 TNM a-Symbol => valueCodeableConcept.coding.code
}
TNM_Klassifikation o--- TNM_a : hasMember
Map TNM_L #22FF22{
    8.13 TNM L-Kategorie => valueCodeableConcept.coding.code
}
TNM_Klassifikation o---- TNM_L : hasMember
Map TNM_Pn #22FF22{
    8.15 TNM Pn-Kategorie => valueCodeableConcept.coding.code
}
TNM_Klassifikation o----- TNM_Pn : hasMember
Map TNM_r #22FF22{
    8.4 TNM r-Symbol => valueCodeableConcept.coding.code
}
TNM_Klassifikation o----- TNM_r : hasMember
Map TNM_S #22FF22{
    8.16 TNM S-Kategorie => valueCodeableConcept.coding.code
}
TNM_Klassifikation o---- TNM_S : hasMember
Map TNM_V #22FF22{
    8.14 TNM V-Kategorie => valueCodeableConcept.coding.code
}
TNM_Klassifikation o--- TNM_V : hasMember
Map TNM_y #22FF22{
    8.3 TNM y-Symbol => valueCodeableConcept.coding.code
}
TNM_Klassifikation o-- TNM_y : hasMember

note bottom of TNM_y
    Legacy-Panel-Profile (TNM_y / TNM_r / TNM_a);
    bevorzugt: modifierExtensions auf T/N/M (8.3–8.5)
end note
note bottom of TNM_r
    Legacy-Panel-Profile (TNM_y / TNM_r / TNM_a);
    bevorzugt: modifierExtensions auf T/N/M (8.3–8.5)
end note
note bottom of TNM_a
    Legacy-Panel-Profile (TNM_y / TNM_r / TNM_a);
    bevorzugt: modifierExtensions auf T/N/M (8.3–8.5)
end note

legend right 
|Color|Type|
|<#FFFF66>|Condition|
|<#CCCCFF>|CarePlan|
|<#9999FF>|Procedure|
|<#DDFFDD>|ServiceRequest|
|<#88FF88>|DiagnosticReport|
|<#22FF22>|Observation|
|<#FFCCFF>|Medication|
|<#FF9999>|AdverseEvent|
|<#44FFFF>|Specimen|
endlegend


@enduml