//skinparam linetype polyline 
//skinparam linetype ortho
@startuml MII_Onko_UML_Relations_v2
skinparam linetype polyline
object Onko_OP #9999FF
object Onko_Strahlentherapie #9999FF
object Onko_SystemischeTherapie #9999FF
object Therapieplanung_Tumorkonferenz #CCCCFF


Therapieplanung_Tumorkonferenz <-- Onko_OP: basedOn 
Therapieplanung_Tumorkonferenz <-- Onko_Strahlentherapie: basedOn
Therapieplanung_Tumorkonferenz <-- Onko_SystemischeTherapie: basedOn
rectangle "Modul Medikation" {
    object MedicationStatement #FFCCFF
}
Onko_SystemischeTherapie <--- MedicationStatement : partOf 
Therapieplanung_Tumorkonferenz <--- MedicationStatement: basedOn
object Diagnose_Primaertumor #FFFF66
object Evidenz_Erstdiagnose #EEEEEE 
Diagnose_Primaertumor --left--> Evidenz_Erstdiagnose : evidence.detail


rectangle "Onkologie Observations"{
    object Onko_Variante #22FF22
    object Fernmetastasen #22FF22
    object TNM_Klassifikation #22FF22
    object WeitereKlassifikation #22FF22 
    object Lymphknotenuntersuchung #22FF22
    object HistologieGrading #22FF22
    object Residualstatus #22FF22
    object Allgemeiner_Leistungszustand #22FF22
    object Tod #22FF22
    object Onko_Befund #88FF88
}

Diagnose_Primaertumor <--- TNM_Klassifikation: focus
Diagnose_Primaertumor <---  Therapieplanung_Tumorkonferenz : addresses
Diagnose_Primaertumor <--- Lymphknotenuntersuchung: focus
Diagnose_Primaertumor <--- HistologieGrading :focus
Diagnose_Primaertumor <--- Onko_Variante :focus
Diagnose_Primaertumor <--- WeitereKlassifikation: focus
Diagnose_Primaertumor <--- Allgemeiner_Leistungszustand :focus
Diagnose_Primaertumor <--- Fernmetastasen :focus

Therapieplanung_Tumorkonferenz <--- Onko_Befund  : basedOn

object Verlauf #22FF22
PrimaerDiagnose <----  Verlauf : focus
Verlauf ---> Tod: hasMember
Verlauf ---> TNM_Klassifikation:  hasMember
Verlauf --->  Lymphknotenuntersuchung : hasMember
Verlauf --->  HistologieGrading : hasMember
Verlauf ---> Fernmetastasen: hasMember
Verlauf ---> Residualstatus:  hasMember
Verlauf ---> Onko_Variante: hasMember

rectangle "Modul Pathologiebefund" {
    object MII_PathoAnforderung #DDFFDD
    object MII_PathoBefund #88FF88 
}
MII_PathoBefund <-- MII_PathoAnforderung : request
MII_PathoBefund ----> TNM_Klassifikation : result
MII_PathoBefund ----> WeitereKlassifikation : result
MII_PathoBefund ----> HistologieGrading : result
MII_PathoBefund ----> Fernmetastasen : result
MII_PathoBefund ----> Residualstatus : result
MII_PathoBefund ----> Onko_Variante : result



rectangle "Modul MolGen-Befundbericht" {
    object MII_MolGenAnforderung #DDFFDD
    object MII_MolGenBefund #88FF88
}
MII_MolGenBefund <-- MII_MolGenAnforderung: request

rectangle "Modul Biobank" {
    object MII_Bioprobe #44FFFF
}



MII_MolGenBefund ....> Onko_Variante: result[variant]
MII_PathoAnforderung  ....> PrimaerDiagnose : reasonReference
MII_MolGenAnforderung ....> PrimaerDiagnose: reasonReference
MII_PathoAnforderung ...> MII_Bioprobe: specimen
MII_PathoAnforderung <... MII_Bioprobe: request
MII_MolGenAnforderung ...> MII_Bioprobe: specimen
MII_MolGenAnforderung <... MII_Bioprobe: request

object AdverseEvent #FF9999
Onko_SystemischeTherapie <--- AdverseEvent: suspectEntity.instance
Onko_Strahlentherapie <--- AdverseEvent: suspectEntity.instance

legend right 
|Color|Type|
|<#FFFF66>|Condition|
|<#CCCCFF>|CarePlan|
|<#9999FF>|Procedure|
|<#DDFFDD>|ServiceRequest|
|<#88FF88>|DiagnosticReport|
|<#22FF22>|Observation|
|<#FFCCFF>|Medication|
|<#FF9999>|AdverseEvent|
|<#44FFFF>|Specimen|
endlegend


@enduml