@startuml MII_Onko_13-16_Prozeduren
object MII_Prozedur_2024 #9999FF
Map Onko_Operation #9999FF{
13.1 Intention der Operation => Procedure. extension[Intention].valueCodeableConcept.coding.code
13.2 OP Datum => Procedure.performedDateTime
13.3 OPS => Procedure.code.coding.code 
13.4 OPS Version => Procedure.code.coding.version
13.5 OP Komplikationen => Procedure.complication
10.1 Lokaler Resektionsstatus => Procedure.outcome
}
Map Onko_Strahlentherapie #9999FF{
14.1 Intention der Strahlentherapie => Procedure.extension[Intention].valueCodeableConcept.coding.code
14.2 Strahlentherapie Stellung zu operativer Therapie => Procedure.extension[StellungZurOp].ValueCodeableConcept.coding.code

14.5 Strahlentherapie Beginn => Prodedure.performedPeriod.start
14.6 Strahlentherapie Ende =>Procedure.performedPeriod.end
14.13 Strahlentherapie Ende Grund => Procedure.outcome
}

Map Onko_Strahlentherapie_Bestrahlung #9999FF{
14.3 Strahlentherapie Zielgebiet => Procedure.extension[Bestrahlung].extension[Zielgebiet].codeableConcept.code
14.4 Strahlentherapie Seite Zielgebiet => Procedure.extension[Bestrahlung].extension[Zielgebiet_Lateralität].codeableConcept.code
14.7 Strahlentherapie Applikationsart => Procedure.extension[Bestrahlung].extension[Applikationsart].codeableConcept.code
14.8 Strahlenart => Procedure.extension[Bestrahlung].extension[Strahlenart].codeableConcept.code
14.9 Strahlentherapie Gesamtdosis (Dosis) => Procedure.extension[Bestrahlung].extension[Gesamtdosis].codeableConcept.code
14.10 Strahlentherapie Einzeldosis pro Tag (Dosis) =>Procedure.extension[Bestrahlung].extension[Einzeldosis].codeableConcept.code
14.11 Strahlentherapie Einheit =>Procedure.extension[Bestrahlung].extension[Einheit].codeableConcept.code
14.12 Boost=>Procedure.extension[Bestrahlung].extension[Boost].codeableConcept.code
}

Onko_Strahlentherapie "Extension   " o-- Onko_Strahlentherapie_Bestrahlung

Map Onko_SystemischeTherapie #9999FF{
16.1 Intention der systemischen Therapie => Procedure.extension[Intention].codeableConcept.coding.code
16.2 Systemische Therapie Stellung zu operativer Therapie => Procedure.extension[StellungZurOp].codeableConcept.coding.code
16.3 Art der systemischen oder abwartenden Therapie => Procedure.code[oBDS]
16.6 Systemische Therapie Beginn => Procedure.performedPeriod.start

16.7 Systemische Therapie Ende Grund => Procedure.outcome 

16.8 Systemische Therapie Ende => Procedure.performedPeriod.end
}

Map Onko_Medikation #FFCCFF{

16.4 Systemische Therapie Protokoll => MedicationStatement.note

16.5 Systemische Therapie Substanz => MedicationStatement.medication.medicationCodeableConcept.coding[atcClassDe]
}

object MII_MedicationStatement #FFCCFF
MII_MedicationStatement <|-- Onko_Medikation
Onko_SystemischeTherapie o-- Onko_Medikation

MII_Prozedur_2024 <|--- Onko_Operation
MII_Prozedur_2024 <|--- Onko_Strahlentherapie
MII_Prozedur_2024 <|-- Onko_SystemischeTherapie

object R4_AdverseEvent #FFAAAA

Map Onko_Nebenwirkung #FFAAAA{
    15.1 CTCAE-Grad => AdverseEvent.severity
    15.2 CTCAE-Nebenwirkung / MedDRA-Code => AdverseEvent.code.coding.code 
    15.3 CTCAE-Version => AdverseEvent.code.coding.version
}
R4_AdverseEvent <|--- Onko_Nebenwirkung


Onko_Strahlentherapie o-- Onko_Nebenwirkung
Onko_SystemischeTherapie o-- Onko_Nebenwirkung

legend right 
|Color|Type|
|<#FFFF66>|Condition|
|<#CCCCFF>|CarePlan|
|<#9999FF>|Procedure|
|<#DDFFDD>|ServiceRequest|
|<#88FF88>|DiagnosticReport|
|<#22FF22>|Observation|
|<#FFCCFF>|Medication|
|<#FF9999>|AdverseEvent|
|<#44FFFF>|Specimen|
endlegend
@enduml