@startuml MII_Onko_08_TNM
object R4_Observation #22FF22

Map TNM_Klassifikation #22FF22 {
  8.1 TNM Datum  => effectiveDateTime 
  8.2 TNM Version =>method 
  8.17 UICC Stadium => valueCodeableConcept.coding.code
}
R4_Observation <|-down- TNM_Klassifikation

Map TNM_T #22FF22{
    8.6 TNM c/p-Präfix T => code.extension[MII_EX_Onko_TNM_cp_Praefix].valueCodeableConcept.coding.code
    8.9 TNM T-Kategorie => valueCodeableConcept.coding.code
   }

TNM_Klassifikation o-- TNM_T
Map TNM_N #22FF22{
    8.7 TNM c/p-Präfix N => code.extension[MII_EX_Onko_TNM_cp_Praefix].valueCodeableConcept.coding.code
    8.11 TNM N-Kategorie => valueCodeableConcept.coding.code
   }
TNM_Klassifikation o--- TNM_N
Map TNM_M #22FF22{
    8.8 TNM c/p-Präfix M => code.extension[MII_EX_Onko_TNM_cp_Praefix].valueCodeableConcept.coding.code
    8.12 TNM M-Kategorie => valueCodeableConcept.coding.code
   }
TNM_Klassifikation o---- TNM_M
Map TNM_m #22FF22{
    8.10 TNM m-Symbol => valueCodeableConcept.coding.code
}
TNM_Klassifikation o-- TNM_m
Map TNM_a #22FF22{
    8.5 TNM a-Symbol => valueCodeableConcept.coding.code
}
TNM_Klassifikation o--- TNM_a
Map TNM_L #22FF22{
    8.13 TNM L-Kategorie => valueCodeableConcept.coding.code
}
TNM_Klassifikation o---- TNM_L
Map TNM_Pn #22FF22{
    8.15 TNM Pn-Kategorie => valueCodeableConcept.coding.code
}
TNM_Klassifikation o----- TNM_Pn
Map TNM_r #22FF22{
    8.4 TNM r-Symbol => valueCodeableConcept.coding.code
}
TNM_Klassifikation o----- TNM_r
Map TNM_S #22FF22{
    8.16 TNM S-Kategorie => valueCodeableConcept.coding.code
}
TNM_Klassifikation o---- TNM_S
Map TNM_V #22FF22{
    8.14 TNM V-Kategorie => valueCodeableConcept.coding.code
}
TNM_Klassifikation o--- TNM_V
Map TNM_y #22FF22{
    8.3 TNM y-Symbol => valueCodeableConcept.coding.code
}
TNM_Klassifikation o-- TNM_y

legend right 
|Color|Type|
|<#FFFF66>|Condition|
|<#CCCCFF>|CarePlan|
|<#9999FF>|Procedure|
|<#DDFFDD>|ServiceRequest|
|<#88FF88>|DiagnosticReport|
|<#22FF22>|Observation|
|<#FFCCFF>|Medication|
|<#FF9999>|AdverseEvent|
|<#44FFFF>|Specimen|
endlegend


@enduml