//left to right direction

@startuml
skinparam linetype ortho
top to bottom direction
object Diagnose #FFFF66 {
  Tumor_ID : String
  Primaertumor_ICD_Code : String
  Primaertumor_ICD_Version : Code
  Primaertumor_Diagnosetext : String
  Primaertumor_Topographie_ICD_O : String
  Primaertumor_Topographie_ICD_O_Version : Code
  Primaertumor_Topographie_ICD_O_Freitext : String
  Primaertumor_Diagnosedatum : Date
  Primaertumor_Diagnosesicherung : Code
  Seitenlokalisation : Code
  Fruehere_Tumorerkrankung_ICD_Code: String
  Fruehere_Tumorerkrankung_ICD_Version: Code
  Fruehere_Tumorerkrankung_Freitext: String
  Fruehere_Tumorerkrankung_Diagnosedatum : Date
  Anmerkung : String
}



object Allgemeiner_Leistungszustand  #22FF22 {
  Allgemeiner_Leistungszustand : Code

}

object OP #9999FF {
  OP_Intention : Code
  OP_Datum : String
  OPS: Code
  OPS_Version : Code
  OP_Komplikation : Code
  Anmerkung : String

}

object Strahlentherapie  #9999FF {
  ST_Intention : Code
  ST_Stellung_OP : Code
  ST_Beginn_Datum : Date
  ST_Ende_Datum : Date
  ST_Ende_Grund : Code
  Anmerkung : String
  
}
object Bestrahlung #9999FF {
  ST_Zielgebiet : Code
  ST_Seite_Zielgebiet : Code
  ST_Applikationsart : Code
  Strahlenart : Code
  ST_Gesamtdosis_Dosis : Float
  ST_Einzeldosis_pro_Tag_Dosis : Float
  ST_Einheit : Code
  Boost: Code

}


object Nebenwirkungen_Strahlentherapie_SystemischeTherapie  #FF9999 {
  Nebenwirkungen_nach_CTCAE-Grad  : Code
  Nebenwirkungen_nach_CTCAE-Art  : String
  Nebenwirkungen_nach_CTCAE-Version : Code
}

object Systemische_Therapie  #9999FF {
  Intention_der_systemischen_Therapie : Code
  Systemische_Therapie_Stellung_zu_operativer_Therapie : Code
  Art_der_systemischen_oder_abwartenden_Therapie : Code
  Systemische_Therapie_Protokoll : Code
  Systemische_Therapie_Beginn : Date
  Systemische_Therapie_Substanz : String
  Systemische_Therapie_Ende Grund : Code
  Systemische_Therapie_Ende : Date
}

object Verlauf  #22FF22 {
  Untersuchungsdatum_Verlauf : String
  Gesamtbeurteilung_Tumorstatus : Code
  Verlauf_Lokaler_Tumorstatus : Code
  Verlauf_Tumorstatus_Lymphknoten : Code
  Verlauf_Tumorstatus_Fernmetastasen : Code
  Anmerkung : String
}


object Tumorkonferenz_Therapieplanung #CCCCFF {
  Tumorkonferenz_Datum : String
  Tumorkonferenz_Typ : Code
  Anmerkung : String
}

object Therapieempfehlung #CCCCFF {
  Tumorkonferenz_Therapieempfehlung_Typ : Code
  Tumorkonferenz/Therapieempfehlung_Therapieabweichung_auf_Wunsch_des_Patienten : Code
}


object Tod  #22FF22 {
  Sterbedatum : Date
  Tod_tumorbedingt : Code
  Todesursache_ICD_Version : Code
  Todesursache_ICD : String
}



object Histologie #22FF22 {
  Histologie_ID : String
  Tumor_Histologiedatum : String
  Histologie_EinsendeNr : String
  Morphologie_Code : String
  Morphologie_ICD_O_Version : Code
  Morphologie_Freitext : String
  Grading : Cod
  Anzahl_der_untersuchten_Lymphknoten : Integer
  Anzahl_der_befallenen_Lymphknoten : Integer
  Anzahl_der_untersuchten_Sentinel-Lymphknoten : Integer
  Anzahl_der_befallenen_Sentinel-Lymphknoten : Integer
  Befund : String
}


object TNM_Klassifikation #22FF22 {
  TNM_ID : String
  TNM_Datum : String
  TNM_Version : Code
  TNM_y_Symbol : Code
  TNM_r_Symbol : Code
  TNM_a_Symbol : Code
  TNM_c_p_u_Praefix_T : Code
  TNM_T : Code
  TNM_m_Symbol : String
  TNM_c_p_u_Praefix_N : Code
  TNM_N : Code
  TNM_c_p_u_Praefix_M : Code
  TNM_M : Code
  TNM_L : Code
  TNM_V : Code
  TNM_Pn : Code
  TNM_S : Code
  UICC_Stadium : Code
}


object Weitere_Klassifikation  #22FF22 {
  Hämatoonkologische_und_sonstige_Klassifikationen_Datum : Date
  Hämatoonkologische_und_sonstige_Klassifikationen_Name : String
  Hämatoonkologische_und_sonstige_Klassifikationen_Einstufung  : String
}

object Residualstatus  #22FF22 {
  Beurteilung_des_lokalen_Residualstatus_nach_Abschluss_der_Operation : Code
  Gesamtbeurteilung_des_Residualstatus : Code
}


object Fernmetastasen #22FF22 {
  Datum_der_diagnostischen_Sicherung_von_Fernmetastasen  : String
  Lokalisation_von_Fernmetastase(n)  : Code

}

object Genetische_Variante  #22FF22 {

  Genetische_Variante_Name : String
  Genetische_Variante_Ausprägung : String

}

object Specimen  #44FFFF {

  Identifikation : String
  Ent-/Abnahmezeitpunkt : Date
  Laboreingangszeitpunkt : Date
  Probenart : Code
  Körperstelle : Code
  Kommentar : String
}


Therapieempfehlung "0..*" -- Tumorkonferenz_Therapieplanung
Nebenwirkungen_Strahlentherapie_SystemischeTherapie  "0..*" -- Strahlentherapie
Nebenwirkungen_Strahlentherapie_SystemischeTherapie  "0..*" -- Systemische_Therapie
Verlauf "0..*" ---- "1" Diagnose
Allgemeiner_Leistungszustand "0..*" -- "1" Diagnose
Allgemeiner_Leistungszustand "0..*" -- "1" Verlauf
Specimen "0..*" -- "0..*" Verlauf
Specimen "0..*" -- "1" Diagnose
Specimen "0..*" -- "0..*" OP
Specimen "0..*" -- "0..*" Histologie
Specimen "0..*" -- "0..*" TNM_Klassifikation
Strahlentherapie "0..*" -- "1" Diagnose
Systemische_Therapie "0..*" -- "1" Diagnose
Bestrahlung "0..*" -- "1" Strahlentherapie
Histologie "0..*" -- "1" Diagnose
Histologie "0..*" -- "1" Residualstatus
TNM_Klassifikation "0..*" -- "1" Diagnose
TNM_Klassifikation "0..*" -- "1" OP
OP "0..*" -- "1" Diagnose
TNM_Klassifikation "0..*" -- "1" Verlauf
Histologie "0..*" -- "1" OP
Histologie "0..*" -- "1" Verlauf
Weitere_Klassifikation "0..*" -- "1" Diagnose
Weitere_Klassifikation "0..*" -- "1" Verlauf
Fernmetastasen "0..*" -- "1" Diagnose
Fernmetastasen "0..*" -- "1" Verlauf
Tod "0..1" -- "1" Verlauf
Residualstatus "0..1" -- "1" OP
Residualstatus "0..1" -- "1" Strahlentherapie
Residualstatus "0..1" -- "1" Systemische_Therapie
Tumorkonferenz_Therapieplanung "0..1" -- "1" Diagnose
Genetische_Variante "0..*" -- "1" Diagnose

legend left

|Color|Type|
|<#FFFF66>|Condition|
|<#CCCCFF>|CarePlan|
|<#9999FF>|Procedure|
|<#DDFFDD>|ServiceRequest|
|<#88FF88>|DiagnosticReport|
|<#22FF22>|Observation|
|<#FFCCFF>|Medication|
|<#FF9999>|AdverseEvent|
|<#44FFFF>|Specimen|
endlegend

@enduml