@startuml FhirModulOnkologieTherapy
skinparam linetype ortho

package Modul_Onkologie {

  class Strahlentherapie << ProcedureRadiotherapy >> {
    Intention : Intention
    StellungZurOp : StellungOp
    terminationReason : StrahlentherapieEndeGrund
    performedPeriod : Period
    bodySite : SNOMEDCTBodyStructures
    # Strahlenart : Code
    # Dose : Dose
    # Applikationsart : Code
    # Einzeldosis_pro_Tag : Float
    # Boost: Code
    outcome : Residualstatus
  }

  class Operation << ADT-Procedure-Surgery >> {
    Intention : Intention
    performedDateTime : dateTime
    code : Code
    complication : OpKomplikationen
    outcome : Residualstatus
  }

  class Nebenwirkung << AdverseEvent >> {
    grade.code : CTCAEGrade
    grade.version : URI
    grade.version : String
  }
  Nebenwirkung --> "0..*" Strahlentherapie : suspectEntity.instance

}

@enduml
