@startuml FhirModulOnkologieDiagnosis
skinparam linetype ortho

package Modul_Onkologie {

  class Krebsdiagnose << Krebsdiagnose >> {
    code : Code
    code.version : String
    code.display : String
    # Primaertumor_Topographie_ICD_O : String
    # Primaertumor_Topographie_ICD_O_Version : Catalog
    # Primaertumor_Topographie_ICD_O_Freitext : String
    recordedDate : Date
    Diagnosesicherung : Diagnosesicherung
    Seitenlokalisation : Seitenlokalisation
    # Fruehere_Tumorerkrankung_ICD_Code: String
    # Fruehere_Tumorerkrankung_ICD_Version: Catalog
    # Fruehere_Tumorerkrankung_Freitext: String
    # Fruehere_Tumorerkrankung_Diagnosedatum : Date
  }

}

@enduml
