@startuml MII KDS Erweiterungsmodul Onkologie
object MII_Symptom_Observation #AAFFAA
Map 17_Verlauf #AAFFAA{
    17.1 Untersuchungsdatum Verlauf => Observation.effectiveDateTime
    17.2 Gesamtbeurteilung Tumorstatus => Observation.component[Gesamtbeurteilung].coding.code
    17.3 Tumorstatus Primärtumor => Observation.component[Primaertumor].coding.code
    17.4 Tumorstatus Lymphknoten => Observation.component[Lymphknoten].coding.code
    17.5 Tumorstatus Fernmetastasen => Observation.component[Fernmetastasen].coding.code

}
MII_Symptom_Observation <|-down-- 17_Verlauf

object R4_CarePlan #FFFF88
Map 18_19_Tumorkonferenz_Therapieempfehlung #FFFF88{
    18.1 Tumorkonferenz Therapieplanung Datum => CarePlan.created
    18.2 Tumorkonferenz Therapieplanung Typ => CarePlan.category
    19.1 Tumorkonferenz Therapieempfehlung Typ => CarePlan.activity.detail.code
    19.2 Tumorkonferenz/Therapieempfehlung Therapieabweichung auf Wunsch des Patienten => CarePlan.activityStatus / activityStatusReason
}
R4_CarePlan <|-down-- 18_19_Tumorkonferenz_Therapieempfehlung

Map 20_Tod_Todesursache #AAFFAA {
 20.1 Sterbedatum => Observation.effectiveDateTime 
 20.2 Tod tumorbedingt => Observation.interpretation
 20.3 Todesursache ICD  => Observation.valueCodeableConcept.coding.code
 20.4 Todesursache ICD-Version => Observation.valueCodeableConcept.coding.version
 } 
MII_Symptom_Observation <|-down- 20_Tod_Todesursache

object MII_MolGen_Variante #88FFFF
Map 23_Genetische_Variante #88FFFF {
    23.1 Genetische Variante Name => Observation.component[conclusion-string]
    23.2 Genetische Variante Ausprägung => Observation.component[molecular-consequence]
}

MII_MolGen_Variante <|-down- 23_Genetische_Variante



@enduml