@startuml MII KDS Erweiterungsmodul Onkologie
object MII_Symptom_Observation
Map 9_WeitereKlassifikation{
 09.1 Hämatoonkologische und sonstige Klassifikationen Datum => Observation.effectiveDateTime
 09.2 Hämatoonkologische und sonstige Klassifikationen Name => Observation.code.text
 09.3 Hämatoonkologische und sonstige Klassifikationen Einstufung => Observation.value[x]
}
Map 10_Residualstatus{
    a => b
}
Map 11_Fernmetastasen{
    a => b
}
Map 12_ECOG-Status {
    a => b
}
@enduml