CodeSystem: MII_CS_Onko_Systemische_Therapie_Protokolle
Id: mii-cs-onko-systemische-therapie-protokolle
Title: "MII CS Onkologie Systemische Therapie Protokolle"
Description: "oBDS-spezifisches Codesystem für Protokolle systemischer Therapien"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablecodesystem"
* ^url = "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/CodeSystem/mii-cs-onko-systemische-therapie-protokolle"
* ^status = #active
* ^experimental = false
* insert Publisher
* insert PR_CS_VS_Version
* insert OnkoCRMICodeSystem
* ^caseSensitive = true
* ^valueSet = "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/ValueSet/mii-vs-onko-systemische-therapie-protokolle"
* ^content = #complete

// Protokolle basierend auf Umsetzungsleitfaden_Protokolle_2021-11-15_V4.CSV
* #ABVD "ABVD" "Bleomycin, Dacarbazin, Doxorubicin, Vinblastin"
* #AC "AC" "Cyclophosphamid, Doxorubicin"
* #ACO "ACO" "Cyclophosphamid, Doxorubicin, Vincristin"
* #ADORE "ADORE" "Fluorouracil, Folinsäure, Oxaliplatin"
* #ADR-IFO "ADR-IFO" "Doxorubicin, Ifosfamid, Mesna"
* #AIO "AIO" "Fluorouracil, Folinsäure"
* #AIO-04 "AIO-04" "Fluorouracil, Folinsäure, Oxaliplatin"
* #AIO-Irinotecan "AIO-Irinotecan" "Fluorouracil, Folinsäure, Irinotecan"
* #ARO "ARO" "Fluorouracil, Folinsäure, Oxaliplatin"
* #AVD "AVD" "Dacarbazin, Doxorubicin, Vinblastin"
* #BCD "BCD" "Actinomycin D, Bleomycin, Cyclophosphamid"
* #BEACOPP-basis "BEACOPP basis" "Bleomycin, Cyclophosphamid, Doxorubicin, Etoposid, Procarbazin, Vincristin, Prednison"
* #BEACOPP-eskaliert "BEACOPP eskaliert" "Bleomycin, Cyclophosphamid, Doxorubicin, Etoposid, Procarbazin, Vincristin, Prednison"
* #BEAM "BEAM" "BCNU, Cytarabin, Etoposid, Melphalan"
* #BOLD "BOLD" "Bleomycin, Dacarbazin, Lomustin, Vincristin"
* #BP "BP" "Bendamustin, Prednison"
* #BR "BR" "Bendamustin, Rituximab"
* #BrECADD "BrECADD" "Brentuximab, Cyclophosphamid, Dacarbacin, Doxorubicin, Etoposid, Dexamethason"
* #BuCy "BuCy" "Busulfan, Cyclophosphamid"
* #CAD "CAD" "Cyclophosphamid, Doxorubicin, Dexamethason"
* #CAO "CAO" "Fluorouracil, Folinsäure, Oxaliplatin"
* #CapeOx "CapeOx" "Capecitabin, Oxaliplatin"
* #Cap-Schema "Cap-Schema" "Capecitabin"
* #CarboTax "CarboTax" "Carboplatin, Paclitaxel"
* #CEV "CEV" "Carboplatin, Etoposid, Vincristin"
* #CHOEP "CHOEP" "Cyclophosphamid, Doxorubicin, Etoposid, Vincristin, Prednison"
* #CHOEP-14 "CHOEP-14" "Cyclophosphamid, Doxorubicin, Etoposid, Vincristin, Prednison, G-CSF"
* #CHOEP-21 "CHOEP-21" "Cyclophosphamid, Doxorubicin, Etoposid, Vincristin, Prednison, G-CSF"
* #CHOP "CHOP" "Cyclophosphamid, Doxorubicin, Vincristin, Prednison"
* #CHOP-14 "CHOP-14" "Cyclophosphamid, Doxorubicin, Vincristin, Prednison, G-CSF"
* #CHOP-21 "CHOP-21" "Cyclophosphamid, Doxorubicin, Vincristin, Prednison, G-CSF"
* #CMF "CMF" "Cyclophosphamid, Fluorouracil, Methotrexat"
* #COPP "COPP" "Cyclophosphamid, Procarbazin, Vincristin, Prednison"
* #CV "CV" "Cisplatin, Vinorelbin"
* #DA "DA" "Cytarabin, Daunorubicin"
* #DAC "DAC" "Cyclophosphamid, Docetaxel, Doxorubicin"
* #DC-Doce-Carbo "DC (Doce/Carbo)" "Carboplatin, Docetaxel"
* #DC-Doce-Cyclo "DC (Doce/Cyclo)" "Cyclophosphamid, Docetaxel"
* #DCbH "DCbH" "Carboplatin, Docetaxel, Trastuzumab"
* #DeVIC "DeVIC" "Carboplatin, Etoposid, Ifosfamid, Dexamethason"
* #Dexa-BEAM "Dexa-BEAM" "Carmustin, Cytarabin, Etoposid, Melphalan, Dexamethason"
* #DHAP "DHAP" "Cisplatin, Cytarabin, Dexamethason"
* #DRC "DRC" "Cyclophosphamid, Rituximab, Dexamethason"
* #DVP "DVP" "Cisplatin, Dacarbazin, Vindesin"
* #EC "EC" "Cyclophosphamid, Epirubicin"
* #EC-D "EC-D" "Cyclophosphamid, Docetaxel, Epirubicin"
* #ECF "ECF" "Cisplatin, Epirubicin, Fluorouracil"
* #EC-P "EC-P" "Cyclophosphamid, Epirubicin, Paclitaxel"
* #ELO-Rd "ELO-Rd" "Elotuzumab, Lenalidomid, Dexamethason"
* #EOX "EOX" "Capecitabin, Epirubicin, Oxaliplatin"
* #EXTREME-mit-Carboplatin "EXTREME mit Carboplatin" "Carboplatin, Cetuximab, Fluorouracil"
* #EXTREME-mit-Cisplatin "EXTREME mit Cisplatin" "Cetuximab, Cisplatin, Fluorouracil"
* #FAC "FAC" "Cyclophosphamid, Doxorubicin, Fluorouracil"
* #FC "FC" "Cyclophosphamid, Fludarabin"
* #FCR "FCR" "Cyclophosphamid, Fludarabin, Rituximab"
* #FEC "FEC" "Cyclophosphamid, Epirubicin, Fluorouracil"
* #FEC-Doc "FEC-Doc" "Cyclophosphamid, Docetaxel, Epirubicin, Fluorouracil"
* #FLAG-Ida "FLAG-Ida" "Cytarabin, Fludarabin, Idarubicin, Lenogastrim"
* #FLO "FLO" "Fluorouracil, Folinsäure, Oxaliplatin"
* #FLOT "FLOT" "Docetaxel, Fluorouracil, Folinsäure, Oxaliplatin"
* #Flu-Cam "Flu-Cam" "Alemtuzumab, Fludarabin"
* #FOLFIRI "FOLFIRI" "Fluorouracil, Folinsäure, Irinotecan"
* #Folfirinox "Folfirinox" "Fluorouracil, Folinsäure, Irinotecan, Oxaliplatin"
* #FOLFOX4 "FOLFOX4" "Fluorouracil, Folinsäure, Oxaliplatin"
* #FOLFOX-6 "FOLFOX-6" "Fluorouracil, Folinsäure, Oxaliplatin"
* #FOLFOXIRI "FOLFOXIRI" "Fluorouracil, Folinsäure, Irinotecan, Oxaliplatin"
* #FUFAMI "FUFAMI" "Fluorouracil, Folinsäure, Mitomycin"
* #FUFIRI "FUFIRI" "Fluorouracil, Folinsäure, Irinotecan"
* #FUFOX "FUFOX" "Fluorouracil, Folinsäure, Oxaliplatin"
* #GC-B "GC-B" "Bevacizumab, Carboplatin, Gemcitabin"
* #GDP-Schema "GDP-Schema" "Cisplatin, Gemcitabin, Dexamethason"
* #GELOX "GELOX" "Asparaginase, Gemcitabin, Oxaliplatin"
* #Gem-Carbo "Gem-Carbo" "Carboplatin, Gemcitabin"
* #Gem-Cis "Gem-Cis" "Cisplatin, Gemcitabin"
* #GemTreo "GemTreo" "Gemcitabin, Treosulfan"
* #GOP "GOP" "Gemcitabin, Oxaliplatin, Paclitaxel"
* #HAM-Cytarabin "HAM-Cytarabin" "Cytarabin, Mitoxantron"
* #HD-Protokoll "HD-Protokoll" "BCNU, Rituximab, Thiotepa"
* #ICE "ICE" "Carboplatin, Etoposid, Ifosfamid"
* #IEV "IEV" "Epirubicin, Etoposid, Ifosfamid"
* #IMVP-16 "IMVP-16" "Etoposid, Ifosfamid, Methotrexat"
* #IRd "IRd" "Ixazomib, Lenalidomid, Dexamethason"
* #Knospe "Knospe" "Chlorambucil, Prednison"
* #Knospe-modifiziert "Knospe modifiziert" "Chlorambucil, Rituximab"
* #KRD "KRD" "Carfilzomib, Lenalidomid, Dexamethason"
* #LV5FU2 "LV5FU2" "Fluorouracil, Folinsäure"
* #LV5FU2-modif "LV5FU2 modif." "Fluorouracil, Folinsäure"
* #MAMAC "MAMAC" "Amsacrin, Cytarabin"
* #MATRix "MATRix" "Cytarabin, Methotrexat, Rituximab, Thiotepa"
* #MAV "MAV" "Cytarabin, Etoposid, Mitoxantron"
* #Mayo-Protokoll "Mayo-Protokoll" "Fluorouracil, Folinsäure"
* #M-Cavi "M-Cavi" "Carboplatin, Methotrexat, Vinblastin"
* #MPT "MPT" "Melphalan, Thalidomid, Prednison"
* #M-VAC "M-VAC" "Cisplatin, Doxorubicin, Methotrexat, Vinblastin"
* #PAC "PAC" "Cisplatin, Cyclophosphamid, Doxorubicin"
* #PC "PC" "Bevacizumab, Carboplatin, Paclitaxel"
* #PC-mit-Bevacizumab "PC mit Bevacizumab" "Bevacizumab, Carboplatin, Paclitaxel"
* #PC-ohne-Bevacizumab "PC ohne Bevacizumab" "Carboplatin, Paclitaxel"
* #PCV "PCV" "Lomustin, Procarbazin, Vincristin"
* #PE "PE" "Cisplatin, Etoposid"
* #PEB "PEB" "Bleomycin, Cisplatin, Etoposid"
* #Peg-DoxC "Peg. DoxC" "Carboplatin, Doxorubicin"
* #PEI "PEI" "Cisplatin, Etoposid, Ifosfamid"
* #P-GEMOX "P-GEMOX" "Asparaginase (peg), Gemcitabin, Oxaliplatin"
* #PLF "PLF" "Cisplatin, Fluorouracil, Folinsäure"
* #PVAG-Schema "PVAG-Schema" "Doxorubicin, Gemcitabin, Vinblastin, Prednison"
* #PVBI "PVBI" "Cisplatin, Ifosfamid, Vinblastin"
* #R-BAC "R-BAC" "Bendamustin, Cytarabin, Rituximab"
* #R-Bendamustin "R-Bendamustin" "Bendamustin, Rituximab"
* #R-CHOP "R-CHOP" "Cyclophosphamid, Doxorubicin, Vincristin, Rituximab, Prednison"
* #R-DeVIC "R-DeVIC" "Carboplatin, Etoposid, Ifosfamid, Rituximab, Dexamethason"
* #R-DHAP "R-DHAP" "Cisplatin, Cytarabin, Rituximab, Dexamethason"
* #RD-Schema "RD-Schema" "Lenalidomid, Dexamethason"
* #RevDex "Rev/Dex" "Lenalidomid, Dexamethason"
* #R-GemOx "R-GemOx" "Gemcitabin, Oxaliplatin, Rituximab"
* #R-HAD "R-HAD" "Cytarabin, Rituximab, Dexamethason"
* #R-ICE "R-ICE" "Carboplatin, Etoposid, Ifosfamid, Rituximab"
* #R-MCP "R-MCP" "Chlorambucil, Mitoxantron, Rituximab, Prednison"
* #R-MP "R-MP" "Methotrexat, Procarbazin, Rituximab"
* #S-HAI "S-HAI" "Cytarabin, Idarubicin, G-CSF"
* #S-HAM "S-HAM" "Cytarabin, Mitoxantron, G-CSF"
* #SMILE "SMILE" "Asparaginase, Etoposid, Ifosfamid, Methotrexat, Dexamethason"
* #TAC "TAC" "Cyclophosphamid, Docetaxel, Doxorubicin"
* #TCED "TCED" "Cyclophosphamid, Etoposid, Thalidomid, Dexamethason"
* #TCH "TCH" "Carboplatin, Docetaxel, Trastuzumab"
* #TIP "TIP" "Cisplatin, Ifosfamid, Paclitaxel"
* #TMZ "TMZ" "Temozolomid"
* #TPF "TPF" "Cisplatin, Docetaxel, Fluorouracil"
* #VCD "VCD" "Bortezomib, Cyclophosphamid, Dexamethason"
* #VFD "VFD" "Bortezomib, Panobinostat, Dexamethason"
* #VIPD "VIPD" "Carboplatin, Etoposid, Ifosfamid, Dexamethason"
* #VMP "VMP" "Bortezomib, Melphalan, Prednison"
* #VRD "VRD" "Bortezomib, Lenalidomid, Dexamethason"
* #VTD "VTD" "Bortezomib, Thalidomid, Dexamethason"
* #XELOX "XELOX" "Capecitabin, Oxaliplatin"
* #XP "XP" "Capecitabin, Cisplatin"
* #Konditionierung-aemyeloablativ-MAC "Konditionierung, ämyeloablativ (MAC)" "Individuell zu wählende Substanzen"
* #Konditionierung-nicht-myeloablativ-NMA "Konditionierung, nicht myeloablativ (NMA)" "Individuell zu wählende Substanzen"
* #Konditionierung-reduzierte-Intensitaet-RIC "Konditionierung, reduzierte Intensität (RIC)" "Individuell zu wählende Substanzen"
* #Konditionierung-reduzierte-Toxizitaet-RTC "Konditionierung, reduzierte Toxizität (RTC)" "Individuell zu wählende Substanzen"
* #TACE-Doxorubicin-Mitomycin "TACE Doxorubicin-Mitomycin" "Doxorubicin, Mitomycin"
* #TACE-Doxorubicin "TACE Doxorubicin" "Doxorubicin"
* #TACE "TACE" "Individuell zu wählende Substanzen"
* #HIPEC-Cisplatin-Mitomycin "HIPEC Cisplatin-Mitomycin" "Cisplatin, Mitomycin"
* #HIPEC-Mitomycin "HIPEC Mitomycin" "Mitomycin"
* #HIPEC "HIPEC" "Individuell zu wählende Substanzen"
* #HITOC "HITOC" "Individuell zu wählende Substanzen"
* #PIPAC-Cisplatin-Doxorubicin "PIPAC Cisplatin-Doxorubicin" "Cisplatin, Doxorubicin"
* #PIPAC-Cisplatin-Paclitaxel "PIPAC Cisplatin-Paclitaxel" "Cisplatin, Paclitaxel"
* #PIPAC "PIPAC" "Individuell zu wählende Substanzen"
* #Instillation-Harnblase-Mitomycin "Instillation Harnblase Mitomycin" "Mitomycin"
* #Instillation-Harnblase-Doxorubicin "Instillation Harnblase Doxorubicin" "Doxorubicin"
* #Instillation-Harnblase-Chemotherapeutikum "Instillation Harnblase Chemotherapeutikum" "Individuell zu wählende Substanzen"
* #Instillation-Harnblase-BCG "Instillation Harnblase (BCG)" "BCG"
* #Instillation-Intrathekal-Tripel "Instillation Intrathekal Tripel" "Cytarabin, Methotrexat, Dexamethason"
* #Instillation-Intrathekal-Quadrupel "Instillation Intrathekal Quadrupel" "Cytarabin, Methotrexat, Dexamethason, Rituximab"
* #Instillation-intrathekal "Instillation intrathekal" "Individuell zu wählende Substanzen"
* #PUVA-systemisch-oral "PUVA systemisch oral" "Psoralen"
* #Bade-PUVA-topisch "(Bade-) PUVA (topisch)" "Psoralen"
* #Aderlass "Aderlass" "Aderlass"
* #Leukapherese "Leukapherese" "Leukapherese"
* #Plasmapherese "Plasmapherese" "Plasmapherese"
* #TTFields "TTFields" "TTFields"
* #CAR-T-Zelltherapie "CAR-T-Zelltherapie" "Individuell zu wählende Substanzen"