Logical: MII_LM_Modellvorhaben_Genomsequenzierung_Onko
Parent: Element
Id: mii-lm-modellvorhaben-genomsequenzierung-onko
Title: "MII LM Modellvorhaben Genomsequenzierung Onkologie"
Description: "MII LogicalModel Modellvorhaben Genomsequenzierung Onkologie"
* insert Publisher
* insert PR_CS_VS_Version
* ^url = "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/LogicalModel/Modellvorhaben-Genomsequenzierung-Onkologie"
* OnkologieFall 0..* BackboneElement "Onkologie-Fall"
  * Diagnose 1..1 BackboneElement "Diagnose"
    * Haupttumordiagnose 1..1 code "Haupttumordiagnose" "Haupttumordiagnose in ICD-10-GM"
    * WeitereOnkologischeDiagnosen 0..* code "Weitere onkologische Diagnosen" "Optional bei mehreren onkologischen Diagnosen, insbesondere Dokumentation als weiter onkologische Diagnose bei hereditären Tumordispositionssydroms (HT), bei HT zusätzliche Dokumentation ORPHAcode oder AlphaID, ein Code soweit vorhanden ist. Undiagnostizierte Erkrankungen sind mit ORPHA:616874 zu kodieren."
    * Hauptdiagnosedatum 0..1 date "Hauptdiagnosedatum" "Datum der Erstdiagnose der Hauptdiagnose. Wenn Tag unbekannt -> 15. des Monats"
    * ECOGStatus 0..1 code "ECOG-Status" "Eastern Cooperative Oncology Group (ECOG) Performance Status nach 0,1,2,3,4,5,unknown, not applicable"
    * KeimbahndiagnoseVorhanden 0..1 code "Keimbahndiagnose vorhanden" "Ja, Nein, unbekannt"
    * Keimbahndiagnose 0..* code "Keimbahndiagnose" "Keimbahndiagnosen nach ICD-10-GM.Bei Diagnose eines hereditären Tumordispositionssydroms als Teil der OE ist verpflichtend anzugeben mit ICD10 und ORPHA oder AlphaID "
    * HPOPhaenotypisierung 0..* code "Phänotypisierung nach HPO " "Human Phenotype Ontology.Bei Diagnose eines hereditären Tumordispositionssydroms als Teil der OE, wenn vorhanden angeben (optional) "
    * Histologie 1..1 code "Histologie nach ICD-O-3" "Histologische Morphologie und Verhalten nach ICD-O-3"
    * Topographie 1..1 code "Topographie nach ICD-O-3" "Topographie des Tumors nach ICD-O-3"
    * Grading 0..1 code "Differenzierungsgrad" "Gibt den Differenzierungsgrad des Tumors entsprechend der aktuellen TNM-Auflage an,  Bei der Klassifikation sind die einschlägigen Regeln der Literatur (TNM) zu beachten."
    * TNMSchluessel 0..1 string "TNM-Klassifikation" "TNM-Klassifikation des Tumors"
    * TNMSystematik 0..1 code "TNM-Systematik" "TNM-Systematik nach AJCC oder UICC"
    * WeitereKlassifikationen 0..* string "Weitere Klassifikationen" "Weitere Klassifikationen des Tumors zum Diagnosezeitpunkt"
    * DiagnostischeVoruntersuchungen 0..* code "Diagnostische Voruntersuchungen" "Diagnostische Voruntersuchungen zum Diagnosezeitpunkt. Bewertung der durchgeführten genetischen Diagnostik, nur für heriditäre Prädispositionssyndrome/ Erbliche Tumore"
  * Vordiagnostik 0..* BackboneElement "Vordiagnostik"
    * ArtDiagnostik 1..1 code "Diagnostik" "Diagnostik, die vor dem MV Genomseq, durchgeführt wurde (Vorbefunde)"
    * DatumDiagnostik 0..1 date "Datum" "Datum der Diagnostik"
  * MolekulareVorbefunde 0..* BackboneElement "klinisch relevante Ergebnisse der Diagnostik"
    * Gen 1..1 code "Gen" "Gen kodiert nach HGNC"
    * Transkript 0..1 code "Transkript" "Transkript kodiert nach Ensembl/RefSeq"
    * DNAChange 0..1 code "DNA-Veränderung" "DNA-Verändung nach cHGVS"
    * ProteinChange 0..1 code "Protein-Veränderung" "Protein-Veränderung nach pHGVS"
    * TypAlteration 0..1 code "Typ der Alteration" "Typ der Alteration / Variantenklasse nach Sequence ontology (SO)"
    * KomplexeAlteration 0..1 string "Komplexe Alteration" "Ausführliche Beschreibung bei komplexen Alteration z.B. Fusion"
  * SystemischeVortherapien 0..* BackboneElement "Systemische Vortherapien"
    * ArtTherapie 1..1 code "Bezug zur operativen Therapie" "Bezug der Vortherapie zu einer operativen Therapie, z.B. adjuvant, neoadjuvant"
    * IntentionTherapie 0..1 code "Intention" "Intention der Vortherapie, z.B. kurativ, palliativ"
    * Substanz 0..* code "Substanz" "Substanz der Vortherapie nach ATC oder Text bei nicht-ATC-Wirkstoffen"
    * Therapiestart 0..1 date "Startdatum" "Startdatum der Vortherapie. Wenn Datum unbekannt, dann 15. des Monats"
    * Therapieende 0..1 date "Enddatum" "Enddatum der Vortherapie. Wenn Datum unbekannt, dann 15. des Monats"
    * EndeGrund 0..1 code "Ende der Therapie" "Grund für das Ende der Vortherapie"
    * TherapieAnsprechen 0..1 code "Ansprechen" "Therapieansprechen der fallrelevante, systemische Vortherapie (PD: Progression, SD:Stabile Erkrankung, PR:Partielle Remission, CR:Komplette Remission)"
    * TherapieAnsprechenDatum 0..1 date "Datum" "Datum des Ansprechens der Vortherapie"

  

* OnkologieMolekular 0..* BackboneElement "Molekulare Diagnostik"
  * EinfacheVariante 0..* BackboneElement "Einfache Variante inkl. Fusionen im codierenden Bereich"
    * Identifier 0..1 string "Identifier" "interner Identifikator der Variante"
    * Gen 1..1 code "Gen" "Gen kodiert nach HGNC"
    * Transkript 0..1 code "Transkript" "Transkript kodiert nach Ensembl/RefSeq"
    * DNAChange 0..1 code "DNA-Veränderung" "DNA-Verändung nach cHGVS"
    * ProteinChange 0..1 code "Protein-Veränderung" "Protein-Veränderung nach pHGVS"
    * TypAlteration 0..1 code "Typ der Alteration" "Typ der Alteration / Variantenklasse nach Sequence ontology (SO)"
    * Lokalization 0..1 code "Lokalisation der Variante" "Lokalisation im kodierenden, regulatorischen oder intergenischen Bereich"
    * LossOfHeterozygosity 0..1 code "Loss of Heterozygosity (LOH)" "Loss of Heterozygosity (LOH) im Bereich der Variante Ja / Nein"

  * CopyNumberVariante 0..* BackboneElement "Variante mit Kopienzahlveränderung (Copy Number Variation, CNV)"
    * Identifier 0..1 string "Identifier" "interner Identifikator der Variante"
    * CNVTyp 0..* BackboneElement "CNV-Typ" "Komplettverlust, partieller Verlust, Amplifikation" // hier evtl. Mapping der Response options
    * Quellprobe 0..1 code "Art der Quellprobe" "Art der Quellprobe (somatisch oder Keimbahn)"
    * Gen 0..1 code "Gen" "Gen kodiert nach HGNC - falls nur ein Gen betreffend"
    * Chromosom 0..1 code "Chromosom" "Chromosom"
    * CNVStartPosition 0..1 integer "CNV-Start" "Startposition des CNV basierend auf Hg38"
    * CNVEndPosition 0..1 integer "CNV-Ende" "Endposition des CNV basierend auf Hg38"
    * CopyNumber 0..1 integer "Copy Number" "Copy Number"
    * Lokalization 0..1 code "Lokalisation der Variante" "Lokalisation im kodierenden, regulatorischen oder intergenischen Bereich"
  
  * StrukturelleVariante 0..* BackboneElement "Strukturelle Variante"
    * Identifier 0..1 string "Identifier" "interner Identifikator der Variante"
    * Quellprobe 0..1 code "Art der Quellprobe" "Art der Quellprobe (somatisch oder Keimbahn)"
    * Gen 0..1 code "Gen" "N-terminales Gen"
    * GenC 0..1 code "Gen" "C-terminales Gen, falls in-frame und kodierend" 
    * StrukturTyp 0..1 code "Variantentyp" "Variantentyp (Inversion, Translokation, Deletion, Insertion, Duplikation)"
    * Beschreibung  0..1 code "Beschreibung der Variante" "Beschreibung der Variante nach HGVS oder ISCN"
    * Nachweismethode 0..1 code "Nachweismethode" "Nachweismethode (DNA / RNA)"
    * Lokalization 0..1 code "Lokalisation der Variante" "Lokalisation im kodierenden, regulatorischen oder intergenischen Bereich"

  * ExpressionsVariante 0..* BackboneElement "Expressionsvariante"
    * Identifier 0..1 string "Identifier" "interner Identifikator der Variante"
    * Gen 1..1 code "Gen" "Gen kodiert nach HGNC"
    * Expression 0..1 code "Expression" "Expression des Gens (über- oder unterexprimiert)"
    * Bewertungsgrundlage 0..1 string "Bewertungsgrundlage" "Bewertungsgrundlage der Expression (z.B. Vergleichskohorte von 400 Patienten)"
    * TMB 0..1 decimal "Tumor Mutational Burden (TMB)" "Tumor Mutational Burden (TMB) in Mut/Mb"
    * HRD 0..1 code "Homologous Recombination Deficiency (HRD)" "Homologous Recombination Deficiency (HRD) erhöht ja/nein"
    * LST 0..1 code "Large Scale Transition (LST)" "Large Scale Transition (LST) erhöht ja/nein"
    * TAI 0..1 code "Telomeric Allelic Imbalance (TAI)" "Telomeric Allelic Imbalance (TAI) erhöht ja/nein"
    * SBS 0..1 code "Single Base Substitution (SBS)" "Single Base Substitution (SBS) erhöht ja/nein"
    * SBSSignature 0..1 code "Single Base Substitution Signature" "Single Base Substitution Signature"
    * Lokalization 0..1 code "Lokalisation der Variante" "Lokalisation im kodierenden, regulatorischen oder intergenischen Bereich"

  



* OnkologiePlan 0..* BackboneElement "Therapieplan"
  * MolekularesTumorboard 0..* BackboneElement "Molekulares Tumorboard"
    * Datum 1..1 date "Datum" "Datum des Tumorboards"
    * EmpfehlungStudie 0..1 code "Empfehlung Studie" "Empfehlung zur Studienteilnahme ja/nein"
    * EmpfehlungBeratung 0..1 code "Empfehlung humangenetische Beratung" "Empfehlung zu einer humangenetischen Beratung ja/nein"
    * EmpfehlungReevaluation 0..1 code "Empfehlung Reevaluation" "Empfehlung zur Reevaluation der molekularen Diagnostik ja/nein"
    * EmpfehlungOperation 0..1 code "Empfehlung Operation" "Empfehlung zur Operation ja/nein"
    * EmpfehlungOperationArt 0..1 code "empfohlenene Operation" "empfohlenen Operation"
    * EmpfehlungOperationRisikoreduzierend 0..1 code "empfohlene Operation ist riskoreduzierend" "empfohlenen Operation ist riskoreduzierend ja/nein"
    * EmpfehlungOperationTherapeutisch 0..1 code "empfohlene Operation ist therapeutisch" "empfohlenene Operation ist therapeutisch ja/nein"
    * DurchgefuehrteOperation 0..* code "Durchgeführte Operation" "Durchgeführte Operation nach OPS inkl. Version"
  * EmpfohleneStudie 0..* BackboneElement "Empfohlene Studieneinschlüsse"
    * Identifier 0..1 string "Identifier" "interner Identifikator der Studie"
    * Register 0..1 code "Register" "Registersystematik, in dem die StudienID angegeben wird (NCT, EudraCT/CTIS, DRKS, andere, unbekannt)"
    * StudienID 0..1 code "Studie" "StudienID in einer Registersystematik"
    * Studienname 1..1 string "Name der Studie"
    * Substanzen 0..* code "Substanzen" "Substanzen, die in der Studie eingesetzt werden, nach ATC kodiert"
    * Evidenzgrad 0..1 code "Evidenzgrad" "Evidenzgrad"
    * ZusatzverweiseEvidenzgraduierung 0..* string "Zusatzverweise zur Evidenzgraduierung" "Zusatzverweise zur Evidenzgraduierung"
    * Prioritaet 0..1 code "Priorität" "Priorität der Studie, falls mehrere Studien empfohlen wurde. 1 ist höchste Priorität"
    * Variante 0..* code "Variante" "interne VariantenID der Variante, die für die Studie relevant ist"
  * Therapieempfehlung 0..* BackboneElement "String" 
    * Identifier 0..1 string "Identifier" "interner Identifikator der Therapieempfehlung"
    * EmpfehlungTyp 0..1 code "Typ der Empfehlung" "Typ der Empfehlung (z.B. inlabel, offlabel, compassionate use, unknown, secondary preventive)"  
    * Substanz 0..* code "Substanzen" "Substanzen, die empfohlen werden, nach ATC kodiert"
    * Evidenzgrad 0..1 code "Evidenzgrad" "Evidenzgrad (m1A - m4, unbekannt)"
    * Prioritaet 0..1 code "Priorität" "Priorität der Therapieempfehlung, falls mehrere Empfehlungen gegeben wurden. 1 ist höchste Priorität"
    * Variante 0..* code "Variante" "interne VariantenID der Variante, die für die Therapieempfehlung relevant ist"
    * TherapeutischeStrategie 0..1 code "Therapeutische Strategie" "Therapeutische Strategie (z.B. zielgerichtete Therapie, Immuntherapie, Chemotherapie, supportive Therapie)"
  * PraeventiveUntersuchungen 0..* BackboneElement "Präventive Maßnahmen"
    * Identifier 0..1 string "Identifier" "interner Identifikator der präventiven Maßnahme"
    * ArtUntersuchung 0..1 string "Art der Untersuchung" "Art der Untersuchung(z.B. Breast Imaging, MRI, MGR, US;Colonoscopy ; Esophago-gastro-duodenoscopy )"

* OnkologieFollowup 0..* BackboneElement "Follow-up und Umsetzung der Therapieempfehlung"
  * Datum 1..1 date "Datum" "Datum des Follow-up"
  * MetachroneTumore 0..* code "Auftreten Metachroner Tumore" "Auftreten metachroner Tumore ja/nein"
  * MetachroneDiagnose 1..1 code "Diagnose" "Diagnose des metachronen Tumors laut ICD-10"
  * ECOG 0..1 code "ECOG-Status" "Eastern Cooperative Oncology Group (ECOG) Performance Status nach 0,1,2,3,4,5,unknown, not applicable"
  * Vitalstatus 1..1 code "Vitalstatus" "Vitalstatus des Patienten zum Zeitpunkt des Follow-ups (lebend, verstorben, unbekannt)"
  * LetzterKontakt 0..1 date "Letzter Kontakt" "Datum des letzten Kontakts"
  * Todesdatum 0..1 date "Todesdatum" "Datum des Todes"
  * Therapien 0..* BackboneElement "Therapien"
    * reference 1..1 string "Referenz Studien-/ Therapieempfehlung" "Referenz auf Studien- / Therapieempfehlung" 
    * TherapieStart 0..1 date "Startdatum" "Startdatum der Therapie"
    * TherapieEnde 0..1 date "Enddatum" "Enddatum der Therapie"
    * TherapieWirkstoff 0..* code "Wirkstoff" "Wirkstoff der Therapie nach ATC oder Text bei nicht-ATC-Wirkstoffen"
    * TherapieAnsprechen 0..1 code "Ansprechen" "Therapieansprechen der Therapie (PD: Progression, SD:Stabile Erkrankung, PR:Partielle Remission, CR:Komplette Remission)"
    * TherapieAnsprechenDatum 0..1 date "Datum" "Datum des Ansprechens der Vortherapie"
    * TherapieEndeGrund 0..1 code "Ende der Therapie" "Grund für das Ende der Vortherapie"
    * DatenquelleTherapieansprechen 1..1 string "Datenquelle Therapieansprechen" "Datenquelle des Therapieansprechens (z.B. Arztbrief, Entlassungsbericht, Tumordokumentation)"
  * PraeventiveMassnahmen 0..* BackboneElement "Präventive Maßnahmen"
    * reference 1..1 string "Referenz präventive Maßnahme" "interne Referenz auf präventive Maßnahme" 
    * preventiveMeasureResult 1..1 string "Ergebnis der präventiven Maßnahme" "Ergebnis der präventiven Maßnahme (z.B. ohne Befund, benigner Befund, Malignom, unklar)"
    * preventiveMeasureDate 0..1 date "Datum der präventiven Maßnahme" "Datum der präventiven Maßnahme"



    
Mapping: Modellvorhaben-Genomsequenzierung-Onkologie-LogicalModel
Id: Modellvorhaben-Genomsequenzierung-FHIR
Title: "Onkologie LogicalModel MII Onkologie Mapping"
Source: MII_LM_Modellvorhaben_Genomsequenzierung_Onko
* OnkologieFall 
  * Diagnose -> "Condition"
    * Haupttumordiagnose -> "Condition.code.coding.where(system='http://fhir.de/CodeSystem/bfarm/icd-10-gm').code"
    * WeitereOnkologischeDiagnosen -> "Condition.code.coding.where(system='http://fhir.de/CodeSystem/bfarm/icd-10-gm').code"

// Terminology Alignment
// ConceptMaps Modellvorhaben-Genomsequenzierung-SNOMED-CT
// ConceptMaps Modellvorhaben-Genomsequenuzierung-LOINC
// ConceptMap.group.element.target.dependsOn
// StructureMap.rule.documentation
