Logical: MII_LM_Onko
Parent: Element
Id: mii-lm-onko
Title: "MII LM Onkologie"
Description: "MII LogicalModel Modul Onkologie"
* insert Publisher
* insert PR_CS_VS_Version
* insert OnkoCRMILogicalModel
* ^url = "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/LogicalModel/Onkologie"
* Diagnose 0..* BackboneElement "Diagnose"
  * PrimaertumorTumordiagnoseICDCode 0..1 code "Primärtumor Tumordiagnose ICD Code" "Kodierung einer meldepflichtigen Erkrankung nach der aktuellen ICD-GM Version."
  * PrimaertumorTumordiagnoseICDVersion 0..1 string "Primärtumor Tumordiagnose ICD-Version" "Bezeichnung der zur Kodierung verwendeten ICD-GM Version."
  * PrimaertumorTumordiagnoseText 0..1 string "Primärtumor Tumordiagnose Text" "Bezeichnung einer meldepflichtigen Erkrankung."
  * PrimaertumorTopographieICDO 0..1 code "Primärtumor Topographie ICD-O" "Bezeichnung der Topographie einer Erkrankung nach der aktuellen ICD-O Version."
  * PrimaertumorTopographieICDOVersion 0..1 string "Primärtumor Topographie ICD-O-Version" "Bezeichnung der zur Kodierung verwendeten ICD-O Version."
  * PrimaertumorDiagnosedatum 0..1 dateTime "Primärtumor Diagnosedatum" "Datum, angegeben in Tag, Monat und Jahr, an dem die meldepflichtige Diagnose erstmals durch einen Arzt klinisch oder mikroskopisch diagnostiziert wurde."
  * PrimaertumorDiagnosesicherung 0..1 code "Primärtumor Diagnosesicherung" "Höchste erreichte Diagnosesicherheit der Diagnose."
  * PrimaertumorSeitenlokalisation 0..1 code "Primärtumor Seitenlokalisation" "Organspezifische Angabe der betroffenen Seite."
  * FruehereTumorerkrankungen 0..* Condition "Frühere Tumorerkrankungen" "Tumorerkrankungen, die in der Anamnese zu einem früheren Zeitpunkt diagnostiziert/behandelt wurden."
* Histologie 0..* BackboneElement "Histologie"
  * TumorHistologiedatum 0..1 dateTime "Tumor Histologiedatum" "Datum, an dem die Gewebeprobe entnommen wurde."
  * HistologieEinsendenummer 0..1 string "Histologie-Einsendenummer" "Die Histologie-Einsendenummer/Auftragsnummer wird vom Pathologischen Institut beim Eingang des Präparates vergeben."
  * MorphologieCode 0..1 code "Morphologie-Code" "Gibt an, welche Histologie der Tumor aufweist."
  * MorphologieICDOBlueBookVersion 0..1 string "Morphologie ICD-O/Blue Book Version" "Bezeichnung der zur Kodierung verwendeten ICD-O/Blue Book Version."
  * MorphologieFreitext 0..1 string "Morphologie-Freitext" "Gibt die Originalbezeichnung der morphologischen Diagnose an."
  * Grading 0..* code "Grading" "Gibt den Differenzierungsgrad des Tumors entsprechend der aktuellen TNM-Auflage an."
  * AnzahlUntersuchteLymphknoten 0..* decimal "Anzahl der untersuchten Lymphknoten" "Gibt an, wie viele Lymphknoten untersucht wurden (einschließlich Sentinel)."
  * AnzahlBefalleneLymphknoten 0..* decimal "Anzahl der befallenen Lymphknoten" "Gibt an, wie viele Lymphknoten befallen sind (einschließlich Sentinel)."
  * AnzahlUntersuchteSentinelLymphknoten 0..* decimal "Anzahl der untersuchten Sentinel-Lymphknoten" "Gibt an, wie viele Sentinel-Lymphknoten untersucht wurden."
  * AnzahlBefalleneSentinelLymphknoten 0..* decimal "Anzahl der befallenen Sentinel-Lymphknoten" "Gibt an, wie viele Sentinel-Lymphknoten befallen sind."
  * Befund 0..* string "Befund" "Vollständiger Befundbericht des Pathologen."
* TNMKlassifikation 0..* BackboneElement "TNM-Klassifikation"
  * TNMDatum 1..1 dateTime "TNM Datum" "Gibt an, auf welches Datum sich die TNM-Klassifikation bezieht."
  * TNMVersion 1..1 code "TNM Version" "Gibt an, nach welcher Version des TNM klassifiziert wurde."
  * TNMySymbol 0..1 code "TNM y-Symbol" "Gibt an, ob die Klassifikation während oder nach initialer multimodaler Therapie erfolgte."
  * TNMySymbol ^code = $LNC#101658-3 "Cancer staging after multimodality therapy"
  * TNMrSymbol 0..1 code "TNM r-Symbol" "Gibt an, ob die Klassifikation ein Rezidiv beurteilt."
  * TNMrSymbol ^code = $LNC#101659-1 "Cancer staging after tumor recurrence"
  * TNMaSymbol 0..1 code "TNM a-Symbol" "Gibt an, ob die Klassifikation aus Anlass einer Autopsie erfolgte."
  * TNMaSymbol ^code = $LNC#101660-9 "Cancer staging during autopsy" 
  * TNMcpuPraefixT 0..1 code "TNM c/p-Präfix T" "Gibt an, ob die Klassifikation klinisch oder pathologisch erfolgte."
  * TNMcpuPraefixN 0..1 code "TNM c/p-Präfix N" "Gibt an, ob die Klassifikation klinisch oder pathologisch erfolgte."
  * TNMcpuPraefixM 0..1 code "TNM c/p-Präfix M" "Gibt an, ob die Klassifikation klinisch oder pathologisch erfolgte."
  * TNMTKategorie 0..1 code "TNM T-Kategorie" "Ausbreitung des Primärtumors, erfolgt gemäß Tumorentität nach TNM."
  * TNMmSymbol 0..1 code "TNM m-Symbol" "Kennzeichnet Vorhandensein multipler Primärtumoren in einem anatomischen Bezirk."
  * TNMMKategorie 0..1 code "TNM M-Kategorie" "Fehlen oder Vorhandensein von Fernmetastasen, gemäß Tumorentität nach TNM."
  * TNMNKategorie 0..1 code "TNM N-Kategorie" "Ausbreitung von regionären Lymphknotenmetastasen, erfolgt gemäß Tumorentität nach TNM."
  * TNMLKategorie 0..1 code "TNM L-Kategorie" "Lymphgefäßinvasion."
  * TNMLKategorie ^code = $SCT#395715009 "Status of lymphatic (small vessel) invasion by tumor (observable entity)"
  * TNMVKategorie 0..1 code "TNM V-Kategorie" "Veneninvasion."
  * TNMVKategorie ^code = $SCT#371493002 "Status of venous (large vessel) invasion by tumor (observable entity)"
  * TNMPnKategorie 0..1 code "TNM Pn-Kategorie" "Perineuralinvasion."
  * TNMPnKategorie ^code = $SCT#371513001 "Presence of direct invasion by primary malignant neoplasm to nerve (observable entity)"
  * TNMSKategorie 0..1 code "TNM S-Kategorie" "Serumtumormarker."
  * TNMSKategorie ^code = $SCT#399424006 "Serum tumor marker category (observable entity)"
  * UICCStadium 0..1 code "UICC Stadium" "Stadium nach aktuell gültiger TNM-Klassifikation."
* WeitereKlassifikationen 0..* BackboneElement ""
  * WeitereKlassifikationDatum 1..1 date "Hämatoonkologische und sonstige Klassifikationen Datum" "Gibt an, auf welches Datum sich die Klassifikation bezieht."
  * WeitereKlassifikationName 1..1 string "Hämatoonkologische und sonstige Klassifikationen Name" "Name der hämatologischen oder sonstigen Klassifikation. Art der Klassifikation."
  * WeitereKlassifikationEinstufung 1..1 code "Hämatoonkologische und sonstige Klassifikationen Einstufung" "Einstufung gemäß der verwendeten hämatoonkologischen oder sonstigen Klassifikationen."
* Residualstatus 0..* BackboneElement "Residualstatus"
  * LokalerResidualstatus 0..1 code "Beurteilung des lokalen Residualstatus nach Abschluss der Operation" "Lokale Beurteilung der Residualklassifikation nach Resektion, bezieht sich auf das, was reseziert wurde, meist Primärtumor, aber z. B. auch Lebermetastasen."
  * GlobalerResidualstatus 0..1 code "Gesamtbeurteilung des Residualstatus" "Gesamtbeurteilung der Residualklassifikation der Erkrankung einschließlich etwaiger Fernmetastasen."
* Fernmetastasen 0..* BackboneElement "Fernmetastasen"
  * LokalisationFernmetastase 1..1 code "Lokalisation von Fernmetastase(n)" "Lokalisation der Fernmetastase(n)."
  * DatumFernmetase 1..1 date "Datum der diagnostischen Sicherung von Fernmetastasen" "Gibt an, wann die Fernmetastase festgestellt wurde."
* AllgemeinerLeistungszustand 0..* BackboneElement "Allgemeiner Leistungszustand"
  * ECOGKarnofsky 1..1 code "ECOG oder Karnofsky"
* Operation 0..* BackboneElement "Operation"
  * OPIntention 1..1 code "Intention" "Gibt an, mit welchem Ziel die Operation geplant wurde"
  * OPDatum 1..1 code "OP Datum" "Datum der OP"
  * OPSCode  1..* code "OPS Code" "Gibt an, welche Operation durchgeführ wurde. OPS (5-*), so genau wie möglich. Bei paaringen Organen mit Seitenangabe"
  * OPSVersion 1..1 code "OPS Version" "Gibt an, nach welcher Version (Jahr) des OPS klassifiziert wurde (Gültige Bezeichnung nach BfArM)" 
  * OPKomplikation 0..* code "OP Komplikationen" "Gibt an, ob eine oder keine Komplikation aufgetreten ist, bzw. wenn eine aufgetreten ist welche."
* Strahlentherapie 0..* BackboneElement "Strahlentherapie"
  * StrahlentherapieIntention 1..1 code "Intention der Strahlentherapie" "Gibt an, mit welcher Intention die Strahlentherapie geplant wurde."
  * StrahlentherapieStellung  1..1 code "Strahlentherapie Stellung zu operativer Therapie" "Gibt an, in welchem Bezug zu einer operativen Therapie die Bestrahlung steht."
  * StrahlentherapieEndeGrund 0..1 code "Strahlentherapie Ende Grund" "Gibt den Grund an, warum die Strahlentherapie beendet wurde."
  * StrahlentherapieBestrahlung 1..* BackboneElement "Bestrahlung" "Dieser Abschnitt entspricht einer Bestrahlung mit spezifischem Zielgebiet, Methodik und Dosis "
    * StrahlentherapieZielgebiet  1..* code "Strahlentherapie Zielgebiet" "Gibt an, an welcher anatomischen Region die Bestrahlung durchgeführt wurde."
    * StrahlentherapieSeiteZielgebiet 0..*  code "Strahlentherapie Seite Zielgebiet" "Bei Zielgebieten, die durch \"(r, l)\" gekennzeichnet sind, ist eine Seitenangabe Pflicht."
    * StrahlentherapieBeginn  1..1 date "Strahlentherapie Beginn" "Gibt an, wann die Strahlentherapie begonnen wurde."
    * StrahlentherapieEnde  0..1 date "Strahlentherapie Ende" "Gibt an, wann die Strahlentherapie beendet wurde."
    * StrahlentherapieApplikationsart 1..1 code "Strahlentherapie Applikationsart" "Gibt an, mit welcher Technik die Strahlentherapie durchgeführt wurde."
    * StrahlentherapieStrahlenart  1..1 code "Strahlenart" "Angewandte Strahlenart (Strahlung oder metabolische Nuklide)"
    * StrahlentherapieGesamtdosis 0..1 code "Strahlentherapie Gesamtdosis" "Gibt an, mit welcher Gesamtdosis das Zielgebiet bestrahlt wurde (inklusive Boost)."
    * StrahlentherapieEinzeldosis 0..1 code "Strahlentherapie Einzeldosis" "Strahlentherapie Einzeldosis pro Tag (Dosis)"
    * StrahlentherapieEinheit 0..1 code "Strahlentherapie Einheit" "Gibt die Einheit zu der Einzel- oder Gesamtdosis an, mit welcher das Zielgebiet bestrahlt wurde, bzw. bei metabolischer Therapie die Aktivität des verwendeten Radionuklids."
    * StrahlentherapieBoost  0..1 code "Boost" "Angabe, ob ein Boost und falls ja, welche Art von Boost appliziert wurde."
* SystemischeTherapie 0..* BackboneElement "Systemische Therapie" 
  * SystemischeTherapieIntention  1..1 code "Intention der systemischen Therapie" "Intention der systemischen Therapie"
  * SystemischeTherapieStellung  1..1 code "Systemische Therapie Stellung zu operativer Therapie" "Gibt an, in welchem Bezug zu einer operativen Therapie die systemische Therapie steht."
  * SystemischeTherapieArtTherapie 1..1 code "Art der systemischen oder abwartenden Therapie" "Gibt an, welche Art der Therapie bzw. abwartende Strategie durchgeführt wurde."
  * SystemischeTherapieProtokoll 0..1 string "Systemische Therapie Protokoll" "Gibt an, nach welchem Protokoll die Systemtherapie durchgeführt wurde."
  * SystemischeTherapieSubstanz 0..* code "Systemische Therapie Substanz" "Gibt an, mit welcher Substanz die Systemtherapie durchgeführt wurde. Nach Möglichkeit ATC kodiert. Mehrere Substanzen sind jeweils einzeln zu kodieren. "
  * SystemischeTherapieBeginn  0..1 date "Systemische Therapie Beginn" "Gibt an, wann die systemische Therapie begonnen wurde."
  * SystemischeTherapieEnde  0..1 date "Systemische Therapie Ende Grund" "Gibt den Grund an, warum die Systemtherapie beendet wurde."
  * SystemischeTherapieEndeGrund 0..1 code "Systemische Therapie Ende" "Gibt an, wann die systemische Therapie beendet wurde."
* Nebenwirkungen 0..* BackboneElement "Nebenwirkungen"
  * NebenwirkungenCTCAEGrad 1..1 code "Nebenwirkungen nach CTCAE-Grad" "Gibt an, zu welchem Schweregrad von Nebenwirkungen es bei der Bestrahlung oder der systemischen Therapie gekommen ist."
  * NebenwirkungenCTCAEArt 1..1 code "Nebenwirkungen nach CTCAE Art" "Gibt an, zu welcher Nebenwirkung es bei der Bestrahlung oder der systemischen Therapie gekommen ist. Bei der Bestrahlung sind sogenannte akute Nebenwirkungen bis zum 90. Tag nach Bestrahlungsbeginn gemeint."
  * NebenwirkungenCTCAEVersion 1..1 string "Nebenwirkungen nach CTCAE Version" "Für den medizinischen Katalog gültige Versionsbezeichnungen (4, 4.03, 5.0, Sonstige). Gemeint ist die Version des CTCAE-Katalogs, nicht die des MedDRA-Katalogs, aus dem die Codes stammen — CTCAE v4.03 basiert auf MedDRA v12.0."
* Verlauf 0..* BackboneElement "Verlauf"
  * VerlaufDatum 0..* date "Untersuchungsdatum Verlauf" "Datum, an dem die letzte Untersuchung durchgeführt wurde, die zur Einschätzung des Tumorstatus geführt hat."
  * VerlaufBeurteilungTumorstatus 0..* code "Gesamtbeurteilung des Tumorstatus" "Gesamtbeurteilung der Erkrankung unter Berücksichtigung aller Manifestationen."
  * VerlaufTumorstatusPrimaertumor 0..* code "Tumorstatus Primärtumor" "Beurteilung der Situation im Primärtumorbereich."
  * VerlaufTumorstatusLymphknoten 0..* code "Tumorstatus Lymphknoten" "Beurteilung der Situation im Bereich der regionären Lymphknoten."
  * VerlaufTumorstatusMetastasen 0..* code "Tumorstatus Fernmetastasen" "Beurteilung der Situation im Bereich der Fernmetastasen."
* Tumorkonferenz 0..* BackboneElement "Tumorkonferenz und Therapieempfehlung"
  * TumorkonferenzTherapieplanungDatum 1..1 date "Tumorkonferenz Therapieplanung Datum" "Datum der Durchführung der Tumorkonferenz bzw. der sonstigen Therapieplanung."
  * TumorkonferenzTherapieplanungTyp 1..1 code "Tumorkonferenz Therapieplanung Typ" "Typ der Tumorkonferenz bzw. der sonstigen Therapieplanung."
  * TumorkonferenzTherapieempfehlungTyp 1..* code "Tumorkonferenz Therapieempfehlung Typ" "Typ der Therapieempfehlung der Tumorkonferenz (z.B. CH, OP, ST)."
  * TumorkonferenzTherapieempfehlungProtokoll 0..* code "Tumorkonferenz Therapieempfehlung Protokoll" "Empfohlenes Therapieprotokoll bei systemischer Therapie (z.B. FOLFOX4, R-CHOP, AC). Optional, insbesondere bei Kombinationstherapien."
  * TumorkonferenzTherapieempfehlungMedikation 0..* code "Tumorkonferenz Therapieempfehlung Medikation" "Einzelne empfohlene Medikamente/Substanzen der Therapie (z.B. ATC-kodiert). Bei Kombinationstherapien werden mehrere Medikamente angegeben."
  * TumorkonferenzTherapieAbweichungPatientenwunsch 1..* code "Tumorkonferenz/Therapieempfehlung Therapieabweichung auf Wunsch des Patienten" "Abweichung auf Wunsch des Patienten."
* Tod 0..1 BackboneElement "Tod"
  * Sterbedatum 0..1 date "Sterbedatum" "Datum des Todes"
  * TodTumorbedingt 0..1 code "Tod tumorbedingt" "Krebs-Tod-Relation"
  * TodesursacheICD 0..* code "Todesursache ICD" "Todesursache im Sinne des Grundleidens"
  * TodesursacheICDVersion 0..* string "Todesursache ICD Version" "Bezeichnung der zur Kodierung verwendeten ICD-GM-Version"
* GenetischeVariante 0..* BackboneElement "Genetische Variante"
  * GenetischeVarianteName 0..1 string "Genetische Variante Name" "Name der genetischen Variante (z.B. K-ras, BRAFV600, NRAS, C-KIT)"
  * GenetischeVarianteAuspraegung 0..1 code "Genetische Variante Ausprägung" "Ausprägung der genetischen Variante nach oBDS"
* Studienteilnahme 0..* BackboneElement "Studienteilnahme"
  * StudienteilnahmeStatus 0..1 code "Studienteilnahme Status" "Einschluss in eine Studie mit Ethikvotum"
  * StudienteilnahmeDatum 0..1 code "Studienteilnahme Datum" "Erstes Einschlussdatum einer Studie mit Ethikvotum"
  * StudienteilnahmeStudienreferenz 0..1 Reference "Studienteilnahme Studienreferenz" "Referenz zur konkreten Studie (ResearchStudy)"

Mapping: Onkologie-LogicalModel
Id: FHIR
Title: "Onkologie LogicalModel FHIR Mapping"
Source: MII_LM_Onko
* Diagnose -> "Condition"
  * PrimaertumorTumordiagnoseICDCode -> "Condition.code.coding.where(system='http://fhir.de/CodeSystem/bfarm/icd-10-gm').code"
  * PrimaertumorTumordiagnoseICDVersion -> "Condition.code.coding.where(system='http://fhir.de/CodeSystem/bfarm/icd-10-gm').version"
  * PrimaertumorTumordiagnoseText -> "Condition.code.text"
  * PrimaertumorTopographieICDO -> "Condition.bodySite.coding.where(system='http://terminology.hl7.org/CodeSystem/icd-o-3').code"
  * PrimaertumorTopographieICDOVersion -> "Condition.bodySite.coding.where(system='http://terminology.hl7.org/CodeSystem/icd-o-3').version"
  * PrimaertumorDiagnosedatum -> "Condition.assertedDate"
  * PrimaertumorDiagnosesicherung -> "Condition.verificationStatus.coding.where(system='https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/CodeSystem/mii-cs-onko-primaertumor-diagnosesicherung').code"
  * PrimaertumorSeitenlokalisation -> "Condition.bodySite.coding.where(system='https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/CodeSystem/mii-cs-onko-primaertumor-seitenlokalisation').code"
  * FruehereTumorerkrankungen -> "Condition"
* Histologie
  * TumorHistologiedatum -> "Specimen.collection.collectedDateTime"
  * HistologieEinsendenummer -> "Specimen.accessionIdentifier"
  * MorphologieCode -> "Condition.extension.where(url='https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-ex-onko-histology-morphology-behavior-icdo3').valueCodeableConcept.code"
  * MorphologieICDOBlueBookVersion -> "Condition.extension.where(url='https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-ex-onko-histology-morphology-behavior-icdo3').valueCodeableConcept.version"
  * MorphologieFreitext -> "Condition.code.text"
  * Grading -> "Observation.valueCodeableConcept.coding.where(system='https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/CodeSystem/mii-cs-onko-grading').code"
  * AnzahlUntersuchteLymphknoten -> "Observation.code.coding.where(system='http://loinc.org' and code='2708-6').select(%resource.valueQuantity.value)"
  * AnzahlBefalleneLymphknoten -> "Observation.code.coding.where(system='http://loinc.org' and code='21893-3').select(%resource.valueQuantity.value)"
  * AnzahlUntersuchteSentinelLymphknoten -> "Observation.code.coding.where(system='http://loinc.org' and code='85347-3').select(%resource.valueQuantity.value)"
  * AnzahlBefalleneSentinelLymphknoten -> "Observation.code.coding.where(system='http://loinc.org' and code='92832-5').select(%resource.valueQuantity.value)"
  * Befund -> "DiagnosticReport.code.coding.where(system='http://loinc.org' and code='60568-3').select(%resource.conclusion)"
* TNMKlassifikation
  * TNMDatum -> "Observation.effectiveDateTime"
  * TNMVersion -> "Observation.method"
  * TNMySymbol -> "Observation.valueCodeableConcept.coding.code"
  * TNMrSymbol -> "Observation.valueCodeableConcept.coding.code"
  * TNMaSymbol -> "Observation.valueCodeableConcept.coding.code"
  * TNMcpuPraefixT -> "Observation.code.extension.where(url='https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-ex-onko-tnm-cp-praefix').value.coding.code"
  * TNMcpuPraefixN -> "Observation.code.extension.where(url='https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-ex-onko-tnm-cp-praefix').value.coding.code"
  * TNMcpuPraefixM -> "Observation.code.extension.where(url='https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-ex-onko-tnm-cp-praefix').value.coding.code"
  * TNMTKategorie -> "Observation.valueCodeableConcept.coding.code"
  * TNMmSymbol -> "Observation.valueCodeableConcept.coding.code"
  * TNMNKategorie -> "Observation.valueCodeableConcept.coding.code"
  * TNMMKategorie -> "Observation.valueCodeableConcept.coding.code"
  * TNMLKategorie -> "Observation.valueCodeableConcept.coding.code"
  * TNMVKategorie -> "Observation.valueCodeableConcept.coding.code"
  * TNMPnKategorie -> "Observation.valueCodeableConcept.coding.code"
  * TNMSKategorie -> "Observation.valueCodeableConcept.coding.code"
  * UICCStadium -> "Observation.valueCodeableConcept.coding.code"
* WeitereKlassifikationen -> "Observation"
  * WeitereKlassifikationDatum -> "Observation.effectiveDateTime"
  * WeitereKlassifikationName -> "Observation.code.text"
  * WeitereKlassifikationEinstufung -> "Observation.value[x]"
* Residualstatus 
  * LokalerResidualstatus -> "Procedure.outcome"
  * GlobalerResidualstatus -> "Observation.valueCodeableConcept.coding.code"
* Fernmetastasen  
  * LokalisationFernmetastase -> "Observation.bodySite"
  * DatumFernmetase -> "Observation.effectiveDateTime"
* AllgemeinerLeistungszustand
  * ECOGKarnofsky -> "Observation.value[x]"
* Operation
  * OPIntention -> "Procedure.extension.valueCodeableConcept.coding.code"
  * OPDatum -> "Procedure.performedDateTime"
  * OPSCode -> "Procedure.code.coding.code"
  * OPSVersion -> "Procedure.code.coding.version"
  * OPKomplikation -> "Procedure.complication.coding.code"
* Strahlentherapie
  * StrahlentherapieIntention -> "Procedure.extension[Intention].valueCodeableConcept.coding.code"
  * StrahlentherapieStellung -> "Procedure.extension[Stellung].valueCodeableConcept.coding.code"
  * StrahlentherapieEndeGrund -> "Procedure.outcome.coding.code"
  * StrahlentherapieBestrahlung -> "Procedure.extension[Bestrahlung]"
    * StrahlentherapieZielgebiet -> "Procedure.extension[Bestrahlung].extension[Zielgebiet].valueCodeableConcept.coding.code"
    * StrahlentherapieSeiteZielgebiet -> "Procedure.extension[Bestrahlung].extension[Zielgebiet_Lateralitaet].valueCodeableConcept.coding.code"
    * StrahlentherapieBeginn -> "Procedure.performedPeriod.start"
    * StrahlentherapieEnde -> "Procedure.performedPeriod.end"
    * StrahlentherapieApplikationsart -> "Procedure.extension[Bestrahlung].extension[Applikationsart].valueCodeableConcept.coding.code"
    * StrahlentherapieStrahlenart -> "Procedure.extension[Bestrahlung].extension[Strahlenart].valueCodeableConcept.coding.code"
    * StrahlentherapieGesamtdosis -> "Procedure.extension[Bestrahlung].extension[Gesamtdosis].valueQuantity.value"
    * StrahlentherapieEinzeldosis -> "Procedure.extension[Bestrahlung].extension[Einzeldosis].valueQuantity.value"
    * StrahlentherapieEinheit -> "Procedure.extension[Bestrahlung].extension[Einheit].valueCodeableConcept.coding.code"
    * StrahlentherapieBoost -> "Procedure.extension[Bestrahlung].extension[Boost].valueCodeableConcept.coding.code"
  
* SystemischeTherapie
  * SystemischeTherapieIntention -> "Procedure.extension[Intention].valueCodeableConcept.coding.code"
  * SystemischeTherapieStellung -> "Procedure.extension[Stellung].valueCodeableConcept.coding.code"
  * SystemischeTherapieArtTherapie -> "Procedure.code.coding.code"
  * SystemischeTherapieProtokoll -> "MedicationStatement.medicationCodeableConcept.text "
  * SystemischeTherapieSubstanz -> "MedicationStatement.medicationCodeableConcept[atcClassDe].coding.code"
  * SystemischeTherapieBeginn -> "Procedure.performedPeriod.start"
  * SystemischeTherapieEnde -> "Procedure.performedPeriod.end"
  * SystemischeTherapieEndeGrund -> "Procedure.outcome.coding.code"

* Nebenwirkungen 
  * NebenwirkungenCTCAEGrad -> "AdverseEvent.seriousness.coding.code"
  * NebenwirkungenCTCAEArt -> "AdverseEvent.event.coding.code"
  * NebenwirkungenCTCAEVersion -> "AdverseEvent.extension.where(url='https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-ex-onko-nebenwirkung-ctcae-version').valueCodeableConcept"

* Tumorkonferenz
  * TumorkonferenzTherapieplanungDatum -> "CarePlan.created"
  * TumorkonferenzTherapieplanungTyp -> "CarePlan.category"
  * TumorkonferenzTherapieempfehlungTyp -> "RequestGroup.code (Therapy type: CH, OP, ST, etc.)"
  * TumorkonferenzTherapieempfehlungProtokoll -> "RequestGroup.action.code (Protocol: FOLFOX4, R-CHOP, etc.)"
  * TumorkonferenzTherapieempfehlungMedikation -> "MedicationRequest.medicationCodeableConcept (referenced from RequestGroup.action.action.resource)"
  * TumorkonferenzTherapieAbweichungPatientenwunsch -> "CarePlan.activity.detail.status & statusReason"
* Tod
  * Sterbedatum -> "Observation.effectiveDateTime"
  * TodTumorbedingt -> "Observation.interpretation.coding.code"
  * TodesursacheICD -> "Observation.valueCodeableConcept.coding.code" 
  * TodesursacheICDVersion -> "Observation.valueCodeableConcept.coding.version" 

* GenetischeVariante -> "Observation"
  * GenetischeVarianteName -> "Observation.note"
  * GenetischeVarianteAuspraegung -> "Observation.interpretation"
* Studienteilnahme -> "Observation"
  * StudienteilnahmeStatus -> "Observation.valueCodeableConcept.coding.code"
  * StudienteilnahmeDatum -> "Observation.effectiveDateTime"
  * StudienteilnahmeStudienreferenz -> "Observation.focus.where(resolve() is ResearchStudy)"

Mapping: Onkologie-LogicalModel-oBDS
Id: oBDS
Title: "Onkologie LogicalModel oBDS Mapping"
Source: MII_LM_Onko
* Diagnose -> "5" "Diagnose - oBDS Kapitel 5. Amtlicher Feldkatalog: https://basisdatensatz.de"
  * PrimaertumorTumordiagnoseICDCode -> "5.1" "Primärtumor Tumordiagnose ICD Code - Kodierung nach aktueller ICD-10-GM"
  * PrimaertumorTumordiagnoseICDVersion -> "5.2" "Primärtumor Tumordiagnose ICD-Version"
  * PrimaertumorTumordiagnoseText -> "5.3" "Primärtumor Tumordiagnose Text - Klartextbezeichnung der meldepflichtigen Erkrankung"
  * PrimaertumorTopographieICDO -> "5.4" "Primärtumor Topographie ICD-O"
  * PrimaertumorTopographieICDOVersion -> "5.5" "Primärtumor Topographie ICD-O-Version"
  * PrimaertumorDiagnosedatum -> "5.6" "Primärtumor Diagnosedatum - Datum der Erstdiagnose"
  * PrimaertumorDiagnosesicherung -> "5.7" "Primärtumor Diagnosesicherung - höchste erreichte Diagnosesicherheit"
  * PrimaertumorSeitenlokalisation -> "5.8" "Primärtumor Seitenlokalisation"
  * FruehereTumorerkrankungen -> "5.9" "Frühere Tumorerkrankungen - eigenständig kodierte Vordiagnosen; im Profil MII_PR_Onko_Fruehere_Tumorerkrankung sind alle Detailangaben ebenfalls unter 5.9 geführt"
* Histologie -> "6" "Histologie - oBDS Kapitel 6"
  * TumorHistologiedatum -> "6.1" "Tumor Histologiedatum - Datum der Probenentnahme"
  * HistologieEinsendenummer -> "6.2" "Histologie-Einsendenummer bzw. Auftragsnummer des Pathologischen Instituts"
  * MorphologieCode -> "6.3" "Morphologie-Code nach ICD-O-3"
  * MorphologieICDOBlueBookVersion -> "6.4" "Morphologie ICD-O/Blue Book Version"
  * MorphologieFreitext -> "6.5" "Morphologie-Freitext - Originalbezeichnung der morphologischen Diagnose"
  * Grading -> "6.6" "Grading - Differenzierungsgrad nach aktueller TNM-Auflage"
  * AnzahlUntersuchteLymphknoten -> "6.7" "Anzahl der untersuchten Lymphknoten einschließlich Sentinel"
  * AnzahlBefalleneLymphknoten -> "6.8" "Anzahl der befallenen Lymphknoten einschließlich Sentinel"
  * AnzahlUntersuchteSentinelLymphknoten -> "6.9" "Anzahl der untersuchten Sentinel-Lymphknoten"
  * AnzahlBefalleneSentinelLymphknoten -> "6.10" "Anzahl der befallenen Sentinel-Lymphknoten"
  * Befund -> "6.11" "Befund - vollständiger Befundbericht des Pathologen"
* TNMKlassifikation -> "8" "TNM-Klassifikation - oBDS Kapitel 8"
  * TNMDatum -> "8.1" "TNM Datum - Bezugsdatum der Klassifikation"
  * TNMVersion -> "8.2" "TNM Version - verwendete TNM-Auflage"
  * TNMySymbol -> "8.3" "TNM y-Symbol - Klassifikation während oder nach initialer multimodaler Therapie"
  * TNMrSymbol -> "8.4" "TNM r-Symbol - Klassifikation eines Rezidivs"
  * TNMaSymbol -> "8.5" "TNM a-Symbol - Klassifikation aus Anlass einer Autopsie"
  * TNMcpuPraefixT -> "8.6" "TNM c/p-Präfix T"
  * TNMcpuPraefixN -> "8.7" "TNM c/p-Präfix N"
  * TNMcpuPraefixM -> "8.8" "TNM c/p-Präfix M"
  * TNMTKategorie -> "8.9" "TNM T-Kategorie - Ausbreitung des Primärtumors"
  * TNMmSymbol -> "8.10" "TNM m-Symbol - multiple Primärtumoren in einem anatomischen Bezirk"
  * TNMMKategorie -> "8.12" "TNM M-Kategorie - Fehlen oder Vorhandensein von Fernmetastasen"
  * TNMNKategorie -> "8.11" "TNM N-Kategorie - regionäre Lymphknotenmetastasen"
  * TNMLKategorie -> "8.13" "TNM L-Kategorie - Lymphgefäßinvasion"
  * TNMVKategorie -> "8.14" "TNM V-Kategorie - Veneninvasion"
  * TNMPnKategorie -> "8.15" "TNM Pn-Kategorie - Perineuralinvasion"
  * TNMSKategorie -> "8.16" "TNM S-Kategorie - Serumtumormarker"
  * UICCStadium -> "8.17" "UICC Stadium nach aktuell gültiger TNM-Klassifikation"
* WeitereKlassifikationen -> "9" "Weitere Klassifikationen - oBDS Kapitel 9; in den Profilen zweistellig als 09 geführt"
  * WeitereKlassifikationDatum -> "9.1" "Hämatoonkologische und sonstige Klassifikationen Datum - im Profil als 09.1 geführt"
  * WeitereKlassifikationName -> "9.2" "Hämatoonkologische und sonstige Klassifikationen Name - im Profil als 09.2 geführt"
  * WeitereKlassifikationEinstufung -> "9.3" "Hämatoonkologische und sonstige Klassifikationen Einstufung - im Profil als 09.3 geführt"
* Residualstatus -> "10" "Residualstatus - oBDS Kapitel 10"
  * LokalerResidualstatus -> "10.1" "Beurteilung des lokalen Residualstatus nach Abschluss der Operation - im Profil MII_PR_Onko_Operation als Procedure.outcome geführt"
  * GlobalerResidualstatus -> "10.2" "Gesamtbeurteilung des Residualstatus einschließlich etwaiger Fernmetastasen"
* Fernmetastasen -> "11" "Fernmetastasen - oBDS Kapitel 11"
  * LokalisationFernmetastase -> "11.1" "Lokalisation von Fernmetastasen"
  * DatumFernmetase -> "11.2" "Datum der diagnostischen Sicherung von Fernmetastasen"
* AllgemeinerLeistungszustand -> "12" "Allgemeiner Leistungszustand - oBDS Kapitel 12"
  * ECOGKarnofsky -> "12.1" "Allgemeiner Leistungszustand nach ECOG oder Karnofsky - oBDS führt beide Skalen unter derselben Feldnummer"
* Operation -> "13" "Operation - oBDS Kapitel 13"
  * OPIntention -> "13.1" "Intention der Operation"
  * OPDatum -> "13.2" "OP Datum"
  * OPSCode -> "13.3" "OPS - Operationen- und Prozedurenschlüssel"
  * OPSVersion -> "13.4" "OPS Version - Jahresversion nach BfArM"
  * OPKomplikation -> "13.5" "OP Komplikationen"
* Strahlentherapie -> "14" "Strahlentherapie - oBDS Kapitel 14"
  * StrahlentherapieIntention -> "14.1" "Intention der Strahlentherapie"
  * StrahlentherapieStellung -> "14.2" "Strahlentherapie Stellung zu operativer Therapie"
  * StrahlentherapieEndeGrund -> "14.13" "Strahlentherapie Ende Grund"
  * StrahlentherapieBestrahlung -> "14.3-14.12" "Bestrahlung - eine Bestrahlung mit spezifischem Zielgebiet Methodik und Dosis; im oBDS keine eigene Feldnummer sondern Gruppierung der Felder 14.3 bis 14.12"
    * StrahlentherapieZielgebiet -> "14.3" "Strahlentherapie Zielgebiet"
    * StrahlentherapieSeiteZielgebiet -> "14.4" "Strahlentherapie Seite Zielgebiet - Pflichtangabe bei mit r/l gekennzeichneten Zielgebieten"
    * StrahlentherapieBeginn -> "14.5" "Strahlentherapie Beginn"
    * StrahlentherapieEnde -> "14.6" "Strahlentherapie Ende"
    * StrahlentherapieApplikationsart -> "14.7" "Strahlentherapie Applikationsart"
    * StrahlentherapieStrahlenart -> "14.8" "Strahlentherapie Strahlenart"
    * StrahlentherapieGesamtdosis -> "14.9" "Strahlentherapie Gesamtdosis inklusive Boost"
    * StrahlentherapieEinzeldosis -> "14.10" "Strahlentherapie Einzeldosis pro Tag"
    * StrahlentherapieEinheit -> "14.11" "Strahlentherapie Einheit zu Einzel- und Gesamtdosis - in den Profilen als Quantity.unit an 14.9 und 14.10 abgebildet"
    * StrahlentherapieBoost -> "14.12" "Strahlentherapie Boost"
* SystemischeTherapie -> "16" "Systemische Therapie - oBDS Kapitel 16"
  * SystemischeTherapieIntention -> "16.1" "Intention der systemischen Therapie"
  * SystemischeTherapieStellung -> "16.2" "Systemische Therapie Stellung zu operativer Therapie"
  * SystemischeTherapieArtTherapie -> "16.3" "Art der systemischen oder abwartenden Therapie"
  * SystemischeTherapieProtokoll -> "16.4" "Systemische Therapie Protokoll"
  * SystemischeTherapieSubstanz -> "16.6" "Systemische Therapie Substanz - nach Möglichkeit ATC-kodiert"
  * SystemischeTherapieBeginn -> "16.5" "Systemische Therapie Beginn"
  * SystemischeTherapieEnde -> "16.8" "Systemische Therapie Ende - Enddatum; die Kurzbeschreibung im LM ist mit der von SystemischeTherapieEndeGrund vertauscht"
  * SystemischeTherapieEndeGrund -> "16.7" "Systemische Therapie Ende Grund; die Kurzbeschreibung im LM ist mit der von SystemischeTherapieEnde vertauscht"
* Nebenwirkungen -> "15" "Nebenwirkungen der Strahlentherapie und systemischen Therapie - oBDS Kapitel 15"
  * NebenwirkungenCTCAEGrad -> "15.1" "Nebenwirkungen nach CTCAE-Grad"
  * NebenwirkungenCTCAEArt -> "15.2" "Nebenwirkungen nach CTCAE Art"
  * NebenwirkungenCTCAEVersion -> "15.3" "Nebenwirkungen nach CTCAE Version"
* Verlauf -> "17" "Verlauf - oBDS Kapitel 17"
  * VerlaufDatum -> "17.1" "Untersuchungsdatum Verlauf"
  * VerlaufBeurteilungTumorstatus -> "17.2" "Gesamtbeurteilung des Tumorstatus"
  * VerlaufTumorstatusPrimaertumor -> "17.3" "Tumorstatus Primärtumor"
  * VerlaufTumorstatusLymphknoten -> "17.4" "Tumorstatus Lymphknoten"
  * VerlaufTumorstatusMetastasen -> "17.5" "Tumorstatus Fernmetastasen"
* Tumorkonferenz -> "18, 19" "Tumorkonferenz oBDS Kapitel 18 und Therapieempfehlung oBDS Kapitel 19"
  * TumorkonferenzTherapieplanungDatum -> "18.1" "Tumorkonferenz Therapieplanung Datum"
  * TumorkonferenzTherapieplanungTyp -> "18.2" "Tumorkonferenz Therapieplanung Typ"
  * TumorkonferenzTherapieempfehlungTyp -> "19.1" "Tumorkonferenz Therapieempfehlung Typ - z.B. CH OP ST"
  * TumorkonferenzTherapieempfehlungProtokoll -> "19.1 (Erweiterung)" "Empfohlenes Therapieprotokoll - MII-Erweiterung zu 19.1; der oBDS erfasst in 19.1 nur den Therapietyp ohne Protokollangabe"
  * TumorkonferenzTherapieempfehlungMedikation -> "19.1 (Erweiterung)" "Einzelne empfohlene Substanzen - MII-Erweiterung zu 19.1; der oBDS erfasst in 19.1 nur den Therapietyp ohne Substanzangabe"
  * TumorkonferenzTherapieAbweichungPatientenwunsch -> "19.2" "Tumorkonferenz bzw. Therapieempfehlung Therapieabweichung auf Wunsch des Patienten"
* Tod -> "20" "Tod - oBDS Kapitel 20"
  * Sterbedatum -> "20.1" "Sterbedatum"
  * TodTumorbedingt -> "20.2" "Tod tumorbedingt - Krebs-Tod-Relation"
  * TodesursacheICD -> "20.3" "Todesursache ICD im Sinne des Grundleidens"
  * TodesursacheICDVersion -> "20.4" "Todesursache ICD-Version"
* GenetischeVariante -> "23" "Genetische Variante - oBDS Kapitel 23"
  * GenetischeVarianteName -> "23.1" "Genetische Variante Name - z.B. K-ras BRAFV600 NRAS C-KIT"
  * GenetischeVarianteAuspraegung -> "23.2" "Genetische Variante Ausprägung"
* Studienteilnahme -> "24" "Studienteilnahme - oBDS Kapitel 24"
  * StudienteilnahmeStatus -> "24.1" "Studienteilnahme Status - Einschluss in eine Studie mit Ethikvotum"
  * StudienteilnahmeDatum -> "24.2" "Studienteilnahme Datum - erstes Einschlussdatum"
  * StudienteilnahmeStudienreferenz -> "kein oBDS-Feld" "Referenz auf die konkrete Studie als ResearchStudy - MII-Ergänzung; der oBDS benennt Studien nur im pädiatrischen Zusatzmodul DKKR/GPOH mit Studienname und Studiennummer nicht in Kapitel 24"
