CodeSystem: MII_CS_Onko_Fernmetastasen_Lokalisation
Id: mii-cs-onko-fernmetastasen-lokalisation
Title: "MII CS Onko Fernmetastasen-Lokalisation"
Description: "Lokalisation von Fernmetastasen"
* #PUL "Lunge"
* #OSS "Knochen"
* #HEP "Leber"
* #BRA "Hirn"
* #LYM "Lymphknoten"
* #MAR "Knochenmark"
* #PLE "Pleura"
* #PER "Peritoneum"
* #ADR "Nebennieren"
* #SKI "Haut"
* #OTH "andere Organe"
* #GEN "generalisierte Metastasierung"
