Logical: MII_LM_Onko_Organspezifische_Zusatzmodule
Parent: Element
Id: mii-lm-onko-organspezifische-zusatzmodule
Title: "MII LM Onkologie Organspezifische Zusatzmodule"
Description: "Logisches Modell für die organspezifischen Zusatzmodule des oBDS. Feldnummern und Struktur folgen dem amtlichen oBDS-XML-Schema (oBDS v3.0.5, Modul_Mamma/Darm/Prostata/Malignes_Melanom/Allgemein) sowie dem Feldkatalog auf basisdatensatz.de."
* insert Publisher
* insert PR_CS_VS_Version
* ^url = "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/LogicalModel/OrganspezifischeZusatzmodule"

* Mamma 0..* BackboneElement "Mamma" "Organspezifisches Modul Mammakarzinom, oBDS M1–M8 (XSD Modul_Mamma_Typ)"
  * Menopausenstatus 0..1 CodeableConcept "Menopausenstatus" "Prätherapeutischer Menopausenstatus einer Patientin mit Mamma-Karzinom. oBDS M1"
  * RezeptorstatusEstrogen 0..1 BackboneElement "Rezeptorstatus Estrogen" "Hormonrezeptorstatus Östrogen. oBDS M2 (XSD: HormonrezeptorStatus_Oestrogen)"
    * Status 0..1 CodeableConcept "Estrogen-Rezeptorstatus" "Kategoriale Bewertung des Estrogen-Rezeptorstatus: positiv/negativ. oBDS M2"
    * AnteilPositiveZellen 0..1 Quantity "Anteil positive Zellen" "Quantitative Bestimmung in Prozent. Komponente zu oBDS M2 (keine eigene Feldnummer, S3-Leitlinie)."
    * Faerbeintensitaet 0..1 CodeableConcept "Färbeintensität" "Qualitative Bewertung der Färbeintensität. Komponente zu oBDS M2 (keine eigene Feldnummer, S3-Leitlinie)."
  * RezeptorstatusProgesteron 0..1 BackboneElement "Rezeptorstatus Progesteron" "Hormonrezeptorstatus Progesteron. oBDS M3 (XSD: HormonrezeptorStatus_Progesteron)"
    * Status 0..1 CodeableConcept "Progesteron-Rezeptorstatus" "Kategoriale Bewertung des Progesteron-Rezeptorstatus: positiv/negativ. oBDS M3"
    * AnteilPositiveZellen 0..1 Quantity "Anteil positive Zellen" "Quantitative Bestimmung in Prozent. Komponente zu oBDS M3 (keine eigene Feldnummer, S3-Leitlinie)."
    * Faerbeintensitaet 0..1 CodeableConcept "Färbeintensität" "Qualitative Bewertung der Färbeintensität. Komponente zu oBDS M3 (keine eigene Feldnummer, S3-Leitlinie)."
  * StatusHer2neu 0..1 CodeableConcept "Her2neu-Status" "Her2neu-Status des Tumorgewebes. oBDS M4 (XSD: Her2neuStatus)"
  * PraeoperativeMarkierung 0..* BackboneElement "Präoperative Markierung" "Präoperative Drahtmarkierung durch Bildgebung gesteuert. oBDS M5 (XSD: PraeopDrahtmarkierung)"
    * Modalitaet 0..1 CodeableConcept "Markierungsmodalität" "Art/Steuerung der präoperativen Markierung. Komponente zu oBDS M5."
  * MammaOperation 0..* BackboneElement "Mamma-Operation" "Operative Therapie; kein eigenes oBDS-Modulfeld (Abbildung über oBDS Kapitel 13/OPS)."
    * Operationstyp 0..1 CodeableConcept "Operationstyp" "Art der Mamma-Operation. Kein oBDS-Modulfeld (OPS, oBDS Kapitel 13)."
    * IntraoperativesImaging 0..* CodeableConcept "Intraoperatives Präparatröntgen/Sonografie" "Intraoperative Präparatkontrolle mittels Röntgen/Sonografie. oBDS M6 (XSD: IntraopPraeparatkontrolle)"
  * TumorgroesseInvasiv 0..1 Quantity "Tumorgröße invasives Karzinom" "Größte Ausdehnung des invasiven Karzinoms in mm. oBDS M7 (XSD: TumorgroesseInvasiv)"
  * TumorgroesseDCIS 0..1 Quantity "Tumorgröße DCIS" "Größte Ausdehnung des duktalen Carcinoma in situ in mm. oBDS M8 (XSD: TumorgroesseDCIS)"

* KolorektalesKarzinom 0..* BackboneElement "Kolorektales Karzinom" "Organspezifisches Modul Kolorektales Karzinom, oBDS KR1–KR10 (XSD Modul_Darm_Typ)"
  * TumorLokalisation 0..1 BackboneElement "Tumor Lokalisation"
    * AbstandAnokutanlinie 0..1 Quantity "Abstand Anokutanlinie" "Höhe des Sitzes des Rektumkarzinoms ab Anokutanlinie in cm. oBDS KR1 (XSD: RektumAbstandAnokutanlinie)"
  * BildgebendeVerfahren 0..1 BackboneElement "Bildgebende Verfahren"
    * MRTMesorektale 0..1 BackboneElement "MRT/CT Mesorektale Faszie" "MRT oder Dünnschicht-CT mit Angabe Abstand mesorektale Faszie. oBDS KR5 (XSD: RektumMRTDuennschichtAngabemesorektaleFaszie)"
      * AbstandMesorektale 0..1 Quantity "Abstand Mesorektale Faszie" "Abstand des Tumors zur mesorektalen Faszie in mm bei MRT/CT. oBDS KR5"
      * AbstandNichtVerfuegbarGrund 0..1 CodeableConcept "Grund für fehlende Abstandsmessung" "Grund, warum der Abstand zur mesorektalen Faszie nicht verfügbar ist (nicht durchgeführt/nicht angegeben/unbekannt). Statusangabe zu oBDS KR5."
  * Operation 0..1 BackboneElement "KRK Operation"
    * Operationstyp 0..1 CodeableConcept "Art des Eingriffs" "Art des Eingriffs beim kolorektalen Karzinom. oBDS KR6 (XSD: ArtEingriff)"
    * ASAKlassifikation 0..1 CodeableConcept "ASA-Klassifikation" "American Society of Anesthesiologists Physical Status Classification System. oBDS KR9 (XSD: ASA)"
    * StomaMarkierung 0..1 BackboneElement "Stoma Markierung" "Präoperative Anzeichnung der Stomaposition. oBDS KR7 (XSD: RektumAnzeichnungStomaposition)"
      * Status 0..1 CodeableConcept "Markierungsstatus" "Status der präoperativen Stoma-Markierung. oBDS KR7"
      * StatusGrund 0..1 CodeableConcept "Status Grund" "Grund für Markierungsstatus (geplant/nicht geplant/abgelehnt). Komponente zu oBDS KR7."
  * PathologischeBewertung 0..1 BackboneElement "Pathologische Bewertung"
    * ResektionsraenderAboral 0..1 Quantity "Resektionsrand aboral" "Minimaler Abstand des aboralen Tumorrandes zum aboralen Resektionsrand in mm. oBDS KR2 (XSD: RektumAbstandAboralerResektionsrand)"
    * ResektionsraenderCircumferell 0..1 Quantity "Resektionsrand circumferell" "Minimaler Abstand des Tumors zur circumferentiellen Resektionsebene in mm. oBDS KR3 (XSD: RektumAbstandCircResektionsebene)"
    * TMEQualitaet 0..1 CodeableConcept "TME Qualität" "Qualität des TME-Präparats (Grad 1-3). oBDS KR4 (XSD: RektumQualitaetTME)"
    * RASMutation 0..1 CodeableConcept "RAS-Mutation" "Mutation des K-ras-Onkogens. oBDS KR10 (XSD: RASMutation)"
  * PostoperativeKomplikationen 0..1 BackboneElement "Postoperative Komplikationen"
    * Anastomoseninsuffizienz 0..1 CodeableConcept "Anastomoseninsuffizienz" "Grad der Anastomoseninsuffizienz beim Rektumkarzinom (Grad A/B/C). oBDS KR8 (XSD: GradRektumAnastomoseninsuffizienz)"

* Prostata 0..* BackboneElement "Prostata" "Organspezifisches Modul Prostatakarzinom, oBDS P1–P9 (XSD Modul_Prostata_Typ)"
  * GleasonScore 0..1 BackboneElement "Gleason Score" "Gleason-Score. oBDS P1 (XSD: GleasonScore)"
    * Score 0..1 CodeableConcept "Gleason Score" "Summe aus primärem und sekundärem Pattern. oBDS P1"
    * GradeGroup 0..1 CodeableConcept "Grade Group" "Internationale Standard Grade Group (1-5). Keine eigene oBDS-Feldnummer (ISUP-Ableitung aus P1)."
  * GleasonPattern 0..* BackboneElement "Gleason Pattern" "Gleason Patterns (primär/sekundär/tertiär). Komponenten zu oBDS P1 (keine eigene Feldnummer)."
    * PatternTyp 0..1 CodeableConcept "Pattern Typ" "Primäres, sekundäres oder tertiäres Gleason Pattern."
    * PatternWert 0..1 CodeableConcept "Pattern Wert" "Gleason Pattern Wert (1-5, ab 3 als maligne)."
  * AnlassGleasonScore 0..1 CodeableConcept "Anlass Gleason-Score" "Anlass der Gleason-Score-Bestimmung (Stanze/OP). oBDS P2 (XSD: AnlassGleasonScore)"
  * BiopsieErgebnisse 0..1 BackboneElement "Biopsie Ergebnisse" "Prostatastanzbiopsie-Ergebnisse. oBDS P3–P6"
    * DatumStanzen 0..1 dateTime "Datum der Stanzen" "Datum der Entnahme der Stanzen. oBDS P3 (XSD: DatumStanzen)"
    * AnzahlStanzen 0..1 Quantity "Anzahl Stanzen" "Gesamtanzahl der entnommenen Biopsie-Stanzen. oBDS P4 (XSD: AnzahlStanzen)"
    * AnzahlPositiverStanzen 0..1 Quantity "Anzahl positive Stanzen" "Anzahl der tumorpositiven Stanzen. oBDS P5 (XSD: AnzahlPosStanzen)"
    * KarzinomBefallStanze 0..1 Quantity "Karzinom-Befall je Stanze" "Prozentuale Ausdehnung des Karzinoms in der am stärksten befallenen Stanze. oBDS P6 (XSD: CaBefallStanze)"
  * PSAWert 0..1 Quantity "PSA-Wert" "Prostataspezifisches Antigen in ng/ml für Diagnostik und Verlaufskontrolle. oBDS P7 (XSD: PSA)"
  * DatumPSA 0..1 dateTime "Datum PSA-Wert" "Datum der Blutentnahme zur PSA-Bestimmung. oBDS P8 (XSD: DatumPSA)"
  * ChirurgischeKomplikationen 0..1 BackboneElement "Chirurgische Komplikationen" "Postoperative Komplikation Clavien-Dindo Grad III/IV innerhalb der ersten 6 Monate. oBDS P9 (XSD: KomplPostOP_ClavienDindo)"
    * ClavienDindoGrad 0..1 CodeableConcept "Clavien-Dindo Grad" "Graduierung postoperativer Komplikationen nach Clavien-Dindo. oBDS P9"
    * KomplikationsArt 0..1 CodeableConcept "Komplikationsart" "Spezifische Art der postoperativen Komplikation. Komponente zu oBDS P9 (keine eigene Feldnummer)."

* MalignesMelanom 0..* BackboneElement "Malignes Melanom" "Organspezifisches Modul Malignes Melanom, oBDS MM1–MM4 (XSD Modul_Malignes_Melanom_Typ)"
  * Sicherheitsabstand 0..1 Quantity "Sicherheitsabstand Primärtumor" "Minimaler Sicherheitsabstand zum Primärtumor in mm. oBDS MM1 (XSD: Sicherheitsabstand_Primaertumor)"
  * BreslowTiefe 0..1 Quantity "Tumordicke (Breslow)" "Breslow-Tumordicke in mm beim Malignen Melanom der Haut. oBDS MM2 (XSD: Tumordicke)"
  * LDH 0..1 BackboneElement "Laktatdehydrogenase" "Laktatdehydrogenase als prognostischer Marker. oBDS MM3 (XSD: LDH)"
    * Wert 0..1 Quantity "LDH-Wert" "Laktatdehydrogenase Aktivität in U/L als prognostischer Marker. oBDS MM3"
    * Bewertung 0..1 CodeableConcept "LDH-Bewertung" "Klinische Bewertung des LDH-Werts (normal/erhöht). Komponente zu oBDS MM3."
  * Ulzeration 0..1 CodeableConcept "Ulzeration" "Pathologisches Kriterium der Ulzeration beim Malignen Melanom der Haut. oBDS MM4 (XSD: Ulzeration)"

* ModulAllgemein 0..* BackboneElement "Modul Allgemein" "Organübergreifende Zusatzitems (XSD Modul_Allgemein_Typ). Im Feldkatalog auf basisdatensatz.de noch organbezogen geführt (M9/M10 bzw. KR11/KR12), im oBDS-XML-Schema zentralisiert."
  * Sozialdienstkontakt 0..1 dateTime "Datum des Sozialdienstkontaktes" "Datum des Sozialdienstkontaktes. Web-Feldkatalog: M9 (Mamma) / KR11 (Kolorektal); XSD: Modul_Allgemein.Sozialdienstkontakt"
  * Psychoonkologiekontakt 0..1 dateTime "Datum des Psychoonkologiekontaktes" "Datum des Psychoonkologiekontaktes. XSD: Modul_Allgemein.Psychoonkologiekontakt (kein Feld im Web-Feldkatalog der Organmodule)"
  * Studienteilnahme 0..1 dateTime "Datum der Studienrekrutierung" "Datum der Studienrekrutierung. Web-Feldkatalog: M10 (Mamma) / KR12 (Kolorektal); XSD: Modul_Allgemein.Studienteilnahme"

Mapping: OrganspezifischeZusatzmodule-LogicalModel
Id: FHIR
Title: "Organspezifische Zusatzmodule LogicalModel FHIR Mapping"
Source: MII_LM_Onko_Organspezifische_Zusatzmodule
* Mamma -> "Brustspezifische Datenpunkte"
  * Menopausenstatus -> "Observation.where(code.coding.system='http://snomed.info/sct' and code.coding.code='161712005').valueCodeableConcept"
  * RezeptorstatusEstrogen -> "Observation.where(code.coding.system='http://loinc.org' and code.coding.code='40556-3')"
    * Status -> "Observation.valueCodeableConcept"
    * AnteilPositiveZellen -> "Observation.component.where(code.coding.system='http://snomed.info/sct' and code.coding.code='1234804006').valueQuantity"
    * Faerbeintensitaet -> "Observation.component.where(code.coding.system='http://snomed.info/sct' and code.coding.code='1236874005').valueCodeableConcept"
  * RezeptorstatusProgesteron -> "Observation.where(code.coding.system='http://loinc.org' and code.coding.code='85339-0')"
    * Status -> "Observation.valueCodeableConcept"
    * AnteilPositiveZellen -> "Observation.component.where(code.coding.system='http://snomed.info/sct' and code.coding.code='1234803000').valueQuantity"
    * Faerbeintensitaet -> "Observation.component.where(code.coding.system='http://snomed.info/sct' and code.coding.code='1237278006').valueCodeableConcept"
  * StatusHer2neu -> "Observation.where(code.coding.system='http://loinc.org' and code.coding.code='48676-1').valueCodeableConcept (Profil mii-pr-onko-mamma-status-her2neu)"
  * MammaOperation -> "Procedure.where(meta.profile.contains('https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-mamma-operation'))"
    * Operationstyp -> "Procedure.code"
    * IntraoperativesImaging -> "Procedure.usedCode"
  * PraeoperativeMarkierung -> "Procedure.where(meta.profile.contains('https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-mamma-praeoperative-markierung'))"
    * Modalitaet -> "Procedure.usedCode.coding.where(memberOf('mii-vs-onko-mamma-praeoperative-markierung-modalitaet'))"
  * TumorgroesseInvasiv -> "Observation.valueQuantity (kein dediziertes Profil in v2027)"
  * TumorgroesseDCIS -> "Observation.valueQuantity (kein dediziertes Profil in v2027)"
* KolorektalesKarzinom -> "Bundle/Collection von KRK-spezifischen Ressourcen"
  * TumorLokalisation -> "KRK-spezifische Tumorlokalisation"
    * AbstandAnokutanlinie -> "Observation.where(code.coding.system='http://loinc.org' and code.coding.code='33748-5').valueQuantity"
  * BildgebendeVerfahren -> "KRK-spezifische bildgebende Verfahren"
    * MRTMesorektale -> "Observation.where(code.coding.system='https://radelement.org' and code.coding.code='RDE96')"
      * AbstandMesorektale -> "Observation.valueQuantity"
      * AbstandNichtVerfuegbarGrund -> "Observation.valueCodeableConcept"
  * Operation -> "Procedure.where(meta.profile.contains('https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-krk-operation'))"
    * Operationstyp -> "Procedure.code"
    * ASAKlassifikation -> "Observation.where(code.coding.system='http://loinc.org' and code.coding.code='97816-3').valueCodeableConcept"
    * StomaMarkierung -> "Procedure.where(meta.profile.contains('https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-krk-stoma-markierung'))"
      * Status -> "Procedure.status"
      * StatusGrund -> "Procedure.statusReason"
  * PathologischeBewertung -> "KRK-spezifische pathologische Bewertung"
    * ResektionsraenderAboral -> "Observation.where(code.coding.system='http://loinc.org' and code.coding.code='81175-2').valueQuantity"
    * ResektionsraenderCircumferell -> "Observation.where(code.coding.system='http://loinc.org' and code.coding.code='81176-0').valueQuantity"
    * TMEQualitaet -> "Specimen.where(meta.profile.contains('https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-krk-specimen')).extension"
    * RASMutation -> "Observation (kein dediziertes Profil in v2027; Abbildung über KDS-Modul Molekulares Tumorboard/MolGen)"
  * PostoperativeKomplikationen -> "KRK-spezifische postoperative Komplikationen"
    * Anastomoseninsuffizienz -> "Observation.where(code.coding.system='http://snomed.info/sct' and code.coding.code='361317002').valueCodeableConcept"
* Prostata -> "Bundle/Collection von Prostata-spezifischen Ressourcen"
  * GleasonScore -> "Observation.where(code.coding.system='http://snomed.info/sct' and code.coding.code='372278000') (Profil mii-pr-onko-prostata-gleason-score-gesamt; LOINC-Zweitkodierung 35266-6)"
    * Score -> "Observation.valueCodeableConcept"
    * GradeGroup -> "Observation.where(code.coding.system='http://snomed.info/sct' and code.coding.code='1812491000004107').valueCodeableConcept (Profil mii-pr-onko-prostate-gleason-grade-group; LOINC-Zweitkodierung 94734-1)"
  * GleasonPattern -> "Observation.where(code.coding.memberOf('mii-vs-onko-prostata-gleason-primary-secondary-tertiary'))"
    * PatternTyp -> "Observation.code"
    * PatternWert -> "Observation.valueCodeableConcept"
  * AnlassGleasonScore -> "Observation (Anlass als Komponente/Methode der Gleason-Score-Observation; kein dediziertes Profil in v2027)"
  * BiopsieErgebnisse -> "Observation Collection"
    * DatumStanzen -> "Specimen.collection.collectedDateTime bzw. Observation.effectiveDateTime der Stanzen-Observations"
    * AnzahlStanzen -> "Observation.where(code.coding.system='http://loinc.org' and code.coding.code='33747-0').valueQuantity"
    * AnzahlPositiverStanzen -> "Observation.where(code.coding.system='http://loinc.org' and code.coding.code='33746-2').valueQuantity"
    * KarzinomBefallStanze -> "Observation.where(code.coding.system='http://loinc.org' and code.coding.code='44637-7').valueQuantity"
  * PSAWert -> "Observation.where(code.coding.system='http://loinc.org' and code.coding.code='2857-1').valueQuantity"
  * DatumPSA -> "Observation.where(code.coding.system='http://loinc.org' and code.coding.code='2857-1').effectiveDateTime"
  * ChirurgischeKomplikationen -> "Observation.where(method.coding.system='http://snomed.info/sct' and method.coding.code='789278003')"
    * ClavienDindoGrad -> "Observation.valueCodeableConcept"
    * KomplikationsArt -> "Observation.component.where(code.coding.system='http://loinc.org' and code.coding.code='LA462-5').valueCodeableConcept"
* MalignesMelanom -> "Bundle/Collection von Melanom-spezifischen Ressourcen"
  * Sicherheitsabstand -> "Observation.where(code.coding.system='http://snomed.info/sct' and code.coding.code='396511007').valueQuantity"
  * BreslowTiefe -> "Observation.where(code.coding.system='http://snomed.info/sct' and code.coding.code='106243009').valueQuantity"
  * Ulzeration -> "Observation.where(code.coding.system='http://snomed.info/sct' and code.coding.code='6270001000004106').valueCodeableConcept"
  * LDH -> "Observation.where(code.coding.memberOf('mii-vs-onko-melanom-ldh'))"
    * Wert -> "Observation.valueQuantity"
    * Bewertung -> "Observation.interpretation"
* ModulAllgemein -> "Organübergreifende Ressourcen"
  * Sozialdienstkontakt -> "Procedure.where(code.coding.system='http://snomed.info/sct' and code.coding.code='306238000').performedDateTime (Profil mii-pr-onko-mamma-sozialdienst)"
  * Psychoonkologiekontakt -> "Procedure (kein dediziertes Profil in v2027)"
  * Studienteilnahme -> "ResearchSubject.period.start (Profil mii-pr-onko-studienteilnahme, oBDS Kapitel 24)"

Mapping: oBDS-Mapping
Id: oBDS
Title: "Organspezifische Zusatzmodule LogicalModel oBDS Mapping"
Source: MII_LM_Onko_Organspezifische_Zusatzmodule
* Mamma -> "Modul Mamma (M1–M8)" "Amtlicher Feldkatalog: https://basisdatensatz.de/module/5/mammakarzinom; XSD Modul_Mamma_Typ (oBDS v3.0.5)"
  * Menopausenstatus -> "M1" "Prätherapeutischer Menopausenstatus - oBDS 2021: perimenopausal wird unter prämenopausal subsumiert"
  * RezeptorstatusEstrogen -> "M2" "HormonrezeptorStatus: Östrogen"
    * Status -> "M2" "Kategoriale Bewertung des Estrogen-Rezeptorstatus"
    * AnteilPositiveZellen -> "M2 (Komponente)" "Quantitative Estrogen-Bestimmung in Prozent; keine eigene oBDS-Feldnummer (S3-Leitlinie)"
    * Faerbeintensitaet -> "M2 (Komponente)" "Estrogen-Färbeintensität; keine eigene oBDS-Feldnummer (S3-Leitlinie)"
  * RezeptorstatusProgesteron -> "M3" "HormonrezeptorStatus: Progesteron"
    * Status -> "M3" "Kategoriale Bewertung des Progesteron-Rezeptorstatus"
    * AnteilPositiveZellen -> "M3 (Komponente)" "Quantitative Progesteron-Bestimmung in Prozent; keine eigene oBDS-Feldnummer (S3-Leitlinie)"
    * Faerbeintensitaet -> "M3 (Komponente)" "Progesteron-Färbeintensität; keine eigene oBDS-Feldnummer (S3-Leitlinie)"
  * StatusHer2neu -> "M4" "Her2neu Status"
  * PraeoperativeMarkierung -> "M5" "Präoperative Drahtmarkierung durch Bildgebung gesteuert"
    * Modalitaet -> "M5 (Komponente)" "Modalität der präoperativen Markierung"
  * MammaOperation -> "kein oBDS-Modulfeld" "Operative Therapie über oBDS Kapitel 13 (OP) und OPS"
    * Operationstyp -> "kein oBDS-Modulfeld" "Art der Mamma-Operation (BET, Mastektomie, Lymphknotenoperation, Rekonstruktion) nach OPS"
    * IntraoperativesImaging -> "M6" "Intraoperatives Präparatröntgen/Sonografie"
  * TumorgroesseInvasiv -> "M7" "Tumorgröße Invasives Karzinom"
  * TumorgroesseDCIS -> "M8" "Tumorgröße DCIS"
* KolorektalesKarzinom -> "Modul Kolorektales Karzinom (KR1–KR10)" "Amtlicher Feldkatalog: https://basisdatensatz.de/module/6/kolorektales-karzinom; XSD Modul_Darm_Typ (oBDS v3.0.5)"
  * TumorLokalisation -> "KR1" "Tumorlokalisation und anatomische Bezugspunkte"
    * AbstandAnokutanlinie -> "KR1" "Rektum: Abstand des Tumorunterrandes zur Anokutanlinie"
  * BildgebendeVerfahren -> "KR5" "Bildgebende Verfahren zur präoperativen Beurteilung"
    * MRTMesorektale -> "KR5" "Rektum: MRT oder Dünnschicht-CT durchgeführt mit Angabe Abstand mesorektale Faszie"
      * AbstandMesorektale -> "KR5" "Abstand zur mesorektalen Faszie in mm"
      * AbstandNichtVerfuegbarGrund -> "KR5 (Statusangabe)" "Status: D/N/U (durchgeführt aber nicht angegeben/nicht durchgeführt/unbekannt)"
  * Operation -> "KR6, KR7, KR9" "KRK-spezifische operative Verfahren"
    * Operationstyp -> "KR6" "Art des Eingriffs"
    * ASAKlassifikation -> "KR9" "ASA-Klassifikation"
    * StomaMarkierung -> "KR7" "Rektum: Präoperative Anzeichnung der Stomaposition"
      * Status -> "KR7" "Status der präoperativen Stoma-Markierung"
      * StatusGrund -> "KR7 (Komponente)" "Grund für Markierungsstatus"
  * PathologischeBewertung -> "KR2–KR4, KR10" "Pathologische Bewertung"
    * ResektionsraenderAboral -> "KR2" "Rektum: Minimaler Abstand vom aboralen Resektionsrand"
    * ResektionsraenderCircumferell -> "KR3" "Rektum: Abstand zur circumferentiellen Resektionsebene"
    * TMEQualitaet -> "KR4" "Rektum: Qualität des TME-Präparats"
    * RASMutation -> "KR10" "Mutation K-ras-Onkogen"
  * PostoperativeKomplikationen -> "KR8" "Postoperative Komplikationen"
    * Anastomoseninsuffizienz -> "KR8" "Rektumkarzinom: Anastomoseninsuffizienz"
* Prostata -> "Modul Prostata (P1–P9)" "Amtlicher Feldkatalog: https://basisdatensatz.de/module/4/prostatakarzinom; XSD Modul_Prostata_Typ (oBDS v3.0.5)"
  * GleasonScore -> "P1" "Gleason-Score"
    * Score -> "P1" "Gleason Score Gesamtwert"
    * GradeGroup -> "P1 (abgeleitet)" "Internationale Standard Grade Group (1-5); keine eigene oBDS-Feldnummer (ISUP-Ableitung)"
  * GleasonPattern -> "P1 (Komponente)" "Gleason Patterns (primär/sekundär/tertiär); keine eigene oBDS-Feldnummer"
    * PatternTyp -> "P1 (Komponente)" "Art des Gleason Patterns (primär/sekundär/tertiär)"
    * PatternWert -> "P1 (Komponente)" "Gleason Pattern Wert (1-5, ab 3 maligne)"
  * AnlassGleasonScore -> "P2" "Anlass Gleason (Stanze/OP)"
  * BiopsieErgebnisse -> "P3–P6" "Prostatabiopsie-Ergebnisse"
    * DatumStanzen -> "P3" "Datum der Stanzen"
    * AnzahlStanzen -> "P4" "Anzahl der Stanzen"
    * AnzahlPositiverStanzen -> "P5" "Anzahl der positiven Stanzen"
    * KarzinomBefallStanze -> "P6" "Ca-Befall Stanze (prozentualer Befall der am stärksten befallenen Stanze)"
  * PSAWert -> "P7" "PSA-Wert"
  * DatumPSA -> "P8" "Datum PSA-Wert"
  * ChirurgischeKomplikationen -> "P9" "Postoperative Komplikation (Clavien-Dindo Grad III/IV innerhalb 6 Monate)"
    * ClavienDindoGrad -> "P9" "Clavien-Dindo Klassifikation postoperativer Komplikationen"
    * KomplikationsArt -> "P9 (Komponente)" "Spezifische Art der postoperativen Komplikation; keine eigene oBDS-Feldnummer"
* MalignesMelanom -> "Modul Malignes Melanom (MM1–MM4)" "Amtlicher Feldkatalog: https://basisdatensatz.de/module/3/malignes-melanom; XSD Modul_Malignes_Melanom_Typ (oBDS v3.0.5)"
  * Sicherheitsabstand -> "MM1" "Sicherheitsabstand Primärtumor in mm nach definitivem operativem Eingriff"
  * BreslowTiefe -> "MM2" "Tumordicke (Breslow) in mm - vertikale Tumordicke von der Granularschicht der Epidermis bis zur tiefsten Tumorinvasion"
  * LDH -> "MM3" "LDH als prognostischer Marker beim metastasierten Melanom"
    * Wert -> "MM3" "LDH-Wert in U/L"
    * Bewertung -> "MM3 (Komponente)" "Bewertung des LDH-Werts (normal/erhöht)"
  * Ulzeration -> "MM4" "Ulzeration der Epidermis über dem Melanom (J = Ja, N = Nein, U = Unbekannt)"
* ModulAllgemein -> "Modul Allgemein" "XSD Modul_Allgemein_Typ (oBDS v3.0.5); im Web-Feldkatalog organbezogen als M9/M10 bzw. KR11/KR12 geführt"
  * Sozialdienstkontakt -> "M9 / KR11" "Datum des Sozialdienstkontaktes"
  * Psychoonkologiekontakt -> "Modul_Allgemein" "Datum des Psychoonkologiekontaktes (nur XSD, kein Web-Feldkatalog-Eintrag der Organmodule)"
  * Studienteilnahme -> "M10 / KR12" "Datum der Studienrekrutierung"
