Logical: MII_LM_Onko_Organspezifische_Zusatzmodule
Parent: Element
Id: mii-lm-onko-organspezifische-zusatzmodule
Title: "MII LM Onkologie Organspezifische Zusatzmodule"
Description: "Logisches Modell für die organspezifischen Zusatzmodule des oBDS"
* insert Publisher
* insert PR_CS_VS_Version
* ^url = "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/LogicalModel/OrganspezifischeZusatzmodule"

* Mamma 0..* BackboneElement "Mamma"
  * Menopausenstatus 0..1 CodeableConcept "Menopausenstatus" "Prätherapeutischer Menopausenstatus einer Patientin mit Mamma-Karzinom. oBDS M1"
  * RezeptorstatusEstrogen 0..1 BackboneElement "Rezeptorstatus Estrogen"
    * Status 0..1 CodeableConcept "Estrogen-Rezeptorstatus" "Kategoriale Bewertung des Estrogen-Rezeptorstatus: positiv/negativ. oBDS M2"
    * AnteilPositiveZellen 0..1 Quantity "Anteil positive Zellen" "Quantitative Bestimmung in Prozent."
    * Faerbeintensitaet 0..1 CodeableConcept "Färbeintensität" "Qualitative Bewertung der Färbeintensität."
  * RezeptorstatusProgesteron 0..1 BackboneElement "Rezeptorstatus Progesteron"
    * Status 0..1 CodeableConcept "Progesteron-Rezeptorstatus" "Kategoriale Bewertung des Progesteron-Rezeptorstatus: positiv/negativ. oBDS M3"
    * AnteilPositiveZellen 0..1 Quantity "Anteil positive Zellen" "Quantitative Bestimmung in Prozent."
    * Faerbeintensitaet 0..1 CodeableConcept "Färbeintensität" "Qualitative Bewertung der Färbeintensität."
  * PraeoperativeMarkierung 0..* BackboneElement "Präoperative Markierung"
    * Modalitaet 0..1 CodeableConcept "Markierungsmodalität" "Art der präoperativen Markierung"
  * MammaOperation 0..* BackboneElement "Mamma-Operation"
    * Operationstyp 0..1 CodeableConcept "Operationstyp" "Art der Mamma-Operation."
    * IntraoperativesImaging 0..* CodeableConcept "Intraoperatives Imaging" "Intraoperatives Imagung und weitere Markierungen und Hilfsmittel während der Operation."

* KolorektalesKarzinom 0..* BackboneElement "Kolorektales Karzinom"
  * Placeholder 0..1 string "Placeholder" "Placeholder für KRK-spezifische Datenelemente."
* Prostata 0..* BackboneElement "Prostata"
  * PSAWert 0..1 Quantity "PSA-Wert" "Prostataspezifisches Antigen in ng/ml für Diagnostik und Verlaufskontrolle."
  * GleasonPattern 0..* BackboneElement "Gleason Pattern"
    * PatternTyp 0..1 CodeableConcept "Pattern Typ" "Primäres, sekundäres oder tertiäres Gleason Pattern."
    * PatternWert 0..1 CodeableConcept "Pattern Wert" "Gleason Pattern Wert (1-5, ab 3 als maligne)."
  * GleasonScore 0..1 BackboneElement "Gleason Score"
    * Score 0..1 CodeableConcept "Gleason Score" "Summe aus primärem und sekundärem Pattern."
    * GradeGroup 0..1 CodeableConcept "Grade Group" "Internationale Standard Grade Group (1-5)."
  * BiopsieErgebnisse 0..1 BackboneElement "Biopsie Ergebnisse"
    * AnzahlStanzen 0..1 Quantity "Anzahl Stanzen" "Gesamtanzahl der entnommenen Biopsie-Stanzen."
    * AnzahlPositiverStanzen 0..1 Quantity "Anzahl positive Stanzen" "Anzahl der tumorpositiven Stanzen."
    * KarzinomBefallStanze 0..1 Quantity "Karzinom-Befall je Stanze" "Prozentuale Ausdehnung des Karzinoms in der Stanze."
  * ChirurgischeKomplikationen 0..1 BackboneElement "Chirurgische Komplikationen"
    * ClavienDindoGrad 0..1 CodeableConcept "Clavien-Dindo Grad" "Graduierung postoperativer Komplikationen nach Clavien-Dindo."
    * KomplikationsArt 0..1 CodeableConcept "Komplikationsart" "Spezifische Art der postoperativen Komplikation."
* MalignesMelanom 0..* BackboneElement "Malignes Melanom"
  * Placeholder 0..1 string "Placeholder" "Placeholder für Melanom-spezifische Datenelemente."

Mapping: OrganspezifischeZusatzmodule-LogicalModel
Id: FHIR
Title: "Organspezifische Zusatzmodule LogicalModel FHIR Mapping"
Source: MII_LM_Onko_Organspezifische_Zusatzmodule
* Mamma -> "Brustspezifische Datenpunkte"
  * Menopausenstatus -> "Observation.where(code.coding.system='http://snomed.info/sct' and code.coding.code='161712005').valueCodeableConcept"
  * RezeptorstatusEstrogen -> "Observation.where(code.coding.system='http://loinc.org' and code.coding.code='40556-3')"
    * Status -> "Observation.valueCodeableConcept"
    * AnteilPositiveZellen -> "Observation.component.where(code.coding.system='http://snomed.info/sct' and code.coding.code='1234804006').valueQuantity"
    * Faerbeintensitaet -> "Observation.component.where(code.coding.system='http://snomed.info/sct' and code.coding.code='1236874005').valueCodeableConcept"
  * RezeptorstatusProgesteron -> "Observation.where(code.coding.system='http://loinc.org' and code.coding.code='85339-0')"
    * Status -> "Observation.valueCodeableConcept"
    * AnteilPositiveZellen -> "Observation.component.where(code.coding.system='http://snomed.info/sct' and code.coding.code='1234803000').valueQuantity"
    * Faerbeintensitaet -> "Observation.component.where(code.coding.system='http://snomed.info/sct' and code.coding.code='1237278006').valueCodeableConcept"
  * MammaOperation -> "Procedure.where(meta.profile.contains('https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-mamma-operation'))"
    * Operationstyp -> "Procedure.code"
    * IntraoperativesImaging -> "Procedure.usedCode"
  * PraeoperativeMarkierung -> "Procedure.where(meta.profile.contains('https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-mamma-praeoperative-markierung'))"
    * Modalitaet -> "Procedure.usedCode.coding.where(memberOf('mii-vs-onko-mamma-praeoperative-markierung-modalitaet'))"
* KolorektalesKarzinom -> "Bundle/Collection von KRK-spezifischen Ressourcen"
  * Placeholder -> "Placeholder für KRK-spezifische Implementierung"
* Prostata -> "Bundle/Collection von Prostata-spezifischen Ressourcen"
  * PSAWert -> "Observation.where(code.coding.system='http://loinc.org' and code.coding.code='2857-1').valueQuantity"
  * GleasonPattern -> "Observation.where(code.coding.memberOf('mii-vs-onko-prostata-gleason-primary-secondary-tertiary'))"
    * PatternTyp -> "Observation.code"
    * PatternWert -> "Observation.valueCodeableConcept"
  * GleasonScore -> "Observation.where(code.coding.system='http://loinc.org' and code.coding.code='44642-7')"
    * Score -> "Observation.valueCodeableConcept"
    * GradeGroup -> "Observation.component.where(code.coding.system='http://loinc.org' and code.coding.code='79892-6').valueCodeableConcept"
  * BiopsieErgebnisse -> "Observation Collection"
    * AnzahlStanzen -> "Observation.where(code.coding.system='http://loinc.org' and code.coding.code='33747-0').valueQuantity"
    * AnzahlPositiverStanzen -> "Observation.where(code.coding.system='http://loinc.org' and code.coding.code='33746-2').valueQuantity"
    * KarzinomBefallStanze -> "Observation.where(code.coding.system='http://loinc.org' and code.coding.code='44637-7').valueQuantity"
  * ChirurgischeKomplikationen -> "Observation.where(method.coding.system='http://snomed.info/sct' and method.coding.code='789278003')"
    * ClavienDindoGrad -> "Observation.valueCodeableConcept"
    * KomplikationsArt -> "Observation.component.where(code.coding.system='http://loinc.org' and code.coding.code='LA462-5').valueCodeableConcept"
* MalignesMelanom -> "Bundle/Collection von Melanom-spezifischen Ressourcen"
  * Placeholder -> "Placeholder für Melanom-spezifische Implementierung"

Mapping: oBDS-Mapping
Id: oBDS
Title: "Organspezifische Zusatzmodule LogicalModel oBDS Mapping"
Source: MII_LM_Onko_Organspezifische_Zusatzmodule
* Mamma -> "Mamma-Zusatzmodul nach oBDS" "Basiert auf oBDS Mammakarzinom-Modul: https://www.basisdatensatz.de/module/5/mammakarzinom"
  * Menopausenstatus -> "M1" "Menopausenstatus - oBDS 2021: perimenopausal wird unter prämenopausal subsumiert"
  * RezeptorstatusEstrogen -> "M2.1" "Estrogen-Rezeptorstatus - Duale Kodierung: oBDS-Definition und S3-Leitlinien-Definition"
    * Status -> "M2.1.1" "Kategoriale Bewertung des Estrogen-Rezeptorstatus"
    * AnteilPositiveZellen -> "M2.1.2" "Quantitative Estrogen-Bestimmung in Prozent"
    * Faerbeintensitaet -> "M2.1.3" "Estrogen-Färbeintensität"
  * RezeptorstatusProgesteron -> "M2.2" "Progesteron-Rezeptorstatus"
    * Status -> "M2.2.1" "Kategoriale Bewertung des Progesteron-Rezeptorstatus"
    * AnteilPositiveZellen -> "M2.2.2" "Quantitative Progesteron-Bestimmung in Prozent"
    * Faerbeintensitaet -> "M2.2.3" "Progesteron-Färbeintensität"
  * MammaOperation -> "M4" "Mamma-Operationen"
    * Operationstyp -> "M4.1" "Art der Mamma-Operation (BET, Mastektomie, Lymphknotenoperation, Rekonstruktion)"
    * IntraoperativesImaging -> "M4.2" "Intraoperative Hilfsmittel und Markierungen"
  * PraeoperativeMarkierung -> "M5" "Präoperative Markierung"
    * Modalitaet -> "M5.1" "Modalität der präoperativen Markierung"
* KolorektalesKarzinom -> "KRK-Zusatzmodul" "Placeholder für KRK-spezifische oBDS-Mappings"
* Prostata -> "Prostata-Zusatzmodul nach oBDS" "Organspezifische Erweiterungen für Prostatakarzinom basierend auf oBDS-Modul"
  * PSAWert -> "P1" "PSA-Wert als Tumormarker für Diagnostik und Verlaufskontrolle"
  * GleasonPattern -> "P2" "Gleason Pattern (primär, sekundär, tertiär) für histopathologische Klassifikation"
    * PatternTyp -> "P2.1" "Art des Gleason Patterns (primär/sekundär/tertiär)"
    * PatternWert -> "P2.2" "Gleason Pattern Wert (1-5, ab 3 maligne)"
  * GleasonScore -> "P3" "Gleason Score als Summe der Patterns"
    * Score -> "P3.1" "Gleason Score Gesamtwert"
    * GradeGroup -> "P3.2" "Internationale Standard Grade Group (1-5)"
  * BiopsieErgebnisse -> "P4" "Prostatabiopsie-Ergebnisse"
    * AnzahlStanzen -> "P4.1" "Gesamtanzahl entnommener Biopsie-Stanzen"
    * AnzahlPositiverStanzen -> "P4.2" "Anzahl tumorpositiver Stanzen"
    * KarzinomBefallStanze -> "P4.3" "Prozentuale Ausdehnung Karzinom je Stanze"
  * ChirurgischeKomplikationen -> "P5" "Postoperative Komplikationen nach Prostatektomie"
    * ClavienDindoGrad -> "P5.1" "Clavien-Dindo Klassifikation postoperativer Komplikationen"
    * KomplikationsArt -> "P5.2" "Spezifische Art der postoperativen Komplikation"
* MalignesMelanom -> "Melanom-Zusatzmodul" "Placeholder für Melanom-spezifische oBDS-Mappings"