// GENERIERT + KURATIERT (beads 14w.2, 2026-08-28). Quelle: §65c Manual Plus
// "Krebsprädispositionssyndrom und -gen" (v3) — 96 Listeneinträge, 90 davon zu
// 109 distinkten HGNC-Genen aufgelöst (Expansionen: FANCA-FANCW auf alle
// Fanconi-Gene mit aktuellem HGNC-Symbol, IDH1/2, XP-Aliasse auf ERCC-Symbole).
// Alle Codes gegen den MII-TermServ verifiziert (HGNC 20250704).
// NICHT kodierbar (keine Gene): 11p13-Deletion, 11p15-Defekt, ETV-RUNX1-Fusion,
// Trisomie 18, Trisomie 21, Unbekannt — zytogenetische Aberrationen/Fusionen
// sind über das molekulargenetische Befundmodell (MolGen) abzubilden.
ValueSet: MII_VS_Onko_Praedispositionsgene_HGNC
Id: mii-vs-onko-praedispositionsgene-hgnc
Title: "MII VS Onkologie Krebsprädispositionsgene HGNC"
Description: "Krebsprädispositionsgene der §65c-Liste (Manual Plus, Krebsprädispositionssyndrom und -gen) als HGNC-Gen-IDs, inkl. Expansion der Sammel-Einträge (FANCA-FANCW, IDH1/2, XP-Komplementationsgruppen). Begleitartefakt ohne Profil-Binding (Andockung an die genetischen Profile folgt mit dem Konzept für genetische Marker). Zytogenetische Aberrationen der Quell-Liste (11p13/11p15, Trisomien, ETV-RUNX1-Fusion) sind keine Gene und hier nicht enthalten. Projektseitige Code-Auflösung ohne Gewähr; fachliche Prüfung vor Produktivnutzung erforderlich."
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^status = #active
* ^experimental = false
* insert Publisher
* insert PR_CS_VS_Version
* insert OnkoCRMIValueSet

* http://www.genenames.org/geneId#HGNC:427 "ALK"
* http://www.genenames.org/geneId#HGNC:26837 "AMER1"
* http://www.genenames.org/geneId#HGNC:583 "APC"
* http://www.genenames.org/geneId#HGNC:18318 "ASXL1"
* http://www.genenames.org/geneId#HGNC:795 "ATM"
* http://www.genenames.org/geneId#HGNC:1058 "BLM"
* http://www.genenames.org/geneId#HGNC:1076 "BMPR1A"
* http://www.genenames.org/geneId#HGNC:1097 "BRAF"
* http://www.genenames.org/geneId#HGNC:1100 "BRCA1"
* http://www.genenames.org/geneId#HGNC:1101 "BRCA2"
* http://www.genenames.org/geneId#HGNC:20473 "BRIP1"
* http://www.genenames.org/geneId#HGNC:1149 "BUB1B"
* http://www.genenames.org/geneId#HGNC:1541 "CBL"
* http://www.genenames.org/geneId#HGNC:1833 "CEBPA"
* http://www.genenames.org/geneId#HGNC:30794 "CEP57"
* http://www.genenames.org/geneId#HGNC:16850 "CTR9"
* http://www.genenames.org/geneId#HGNC:2718 "DDB2"
* http://www.genenames.org/geneId#HGNC:17098 "DICER1"
* http://www.genenames.org/geneId#HGNC:28648 "DIS3L2"
* http://www.genenames.org/geneId#HGNC:2890 "DKC1"
* http://www.genenames.org/geneId#HGNC:3309 "ELANE"
* http://www.genenames.org/geneId#HGNC:5959 "ELP1"
* http://www.genenames.org/geneId#HGNC:3374 "EPAS1"
* http://www.genenames.org/geneId#HGNC:11529 "EPCAM"
* http://www.genenames.org/geneId#HGNC:3433 "ERCC1"
* http://www.genenames.org/geneId#HGNC:3434 "ERCC2"
* http://www.genenames.org/geneId#HGNC:3435 "ERCC3"
* http://www.genenames.org/geneId#HGNC:3436 "ERCC4"
* http://www.genenames.org/geneId#HGNC:3437 "ERCC5"
* http://www.genenames.org/geneId#HGNC:3495 "ETV6"
* http://www.genenames.org/geneId#HGNC:3527 "EZH2"
* http://www.genenames.org/geneId#HGNC:3582 "FANCA"
* http://www.genenames.org/geneId#HGNC:3583 "FANCB"
* http://www.genenames.org/geneId#HGNC:3584 "FANCC"
* http://www.genenames.org/geneId#HGNC:3585 "FANCD2"
* http://www.genenames.org/geneId#HGNC:3586 "FANCE"
* http://www.genenames.org/geneId#HGNC:3587 "FANCF"
* http://www.genenames.org/geneId#HGNC:3588 "FANCG"
* http://www.genenames.org/geneId#HGNC:25568 "FANCI"
* http://www.genenames.org/geneId#HGNC:20748 "FANCL"
* http://www.genenames.org/geneId#HGNC:23168 "FANCM"
* http://www.genenames.org/geneId#HGNC:4451 "GPC3"
* http://www.genenames.org/geneId#HGNC:23694 "GPR161"
* http://www.genenames.org/geneId#HGNC:5173 "HRAS"
* http://www.genenames.org/geneId#HGNC:5382 "IDH1"
* http://www.genenames.org/geneId#HGNC:5383 "IDH2"
* http://www.genenames.org/geneId#HGNC:13176 "IKZF1"
* http://www.genenames.org/geneId#HGNC:6407 "KRAS"
* http://www.genenames.org/geneId#HGNC:6764 "MAD2L2"
* http://www.genenames.org/geneId#HGNC:6913 "MAX"
* http://www.genenames.org/geneId#HGNC:7010 "MEN1"
* http://www.genenames.org/geneId#HGNC:7127 "MLH1"
* http://www.genenames.org/geneId#HGNC:7325 "MSH2"
* http://www.genenames.org/geneId#HGNC:7329 "MSH6"
* http://www.genenames.org/geneId#HGNC:7652 "NBN"
* http://www.genenames.org/geneId#HGNC:7765 "NF1"
* http://www.genenames.org/geneId#HGNC:7989 "NRAS"
* http://www.genenames.org/geneId#HGNC:14234 "NSD1"
* http://www.genenames.org/geneId#HGNC:26144 "PALB2"
* http://www.genenames.org/geneId#HGNC:8619 "PAX5"
* http://www.genenames.org/geneId#HGNC:9143 "PHOX2B"
* http://www.genenames.org/geneId#HGNC:8975 "PIK3CA"
* http://www.genenames.org/geneId#HGNC:9122 "PMS2"
* http://www.genenames.org/geneId#HGNC:9181 "POLH"
* http://www.genenames.org/geneId#HGNC:9585 "PTCH1"
* http://www.genenames.org/geneId#HGNC:9588 "PTEN"
* http://www.genenames.org/geneId#HGNC:9644 "PTPN11"
* http://www.genenames.org/geneId#HGNC:9817 "RAD51"
* http://www.genenames.org/geneId#HGNC:9820 "RAD51C"
* http://www.genenames.org/geneId#HGNC:9884 "RB1"
* http://www.genenames.org/geneId#HGNC:9949 "RECQL4"
* http://www.genenames.org/geneId#HGNC:9966 "REST"
* http://www.genenames.org/geneId#HGNC:9967 "RET"
* http://www.genenames.org/geneId#HGNC:25539 "RFWD3"
* http://www.genenames.org/geneId#HGNC:10402 "RPS19"
* http://www.genenames.org/geneId#HGNC:15888 "RTEL1"
* http://www.genenames.org/geneId#HGNC:10471 "RUNX1"
* http://www.genenames.org/geneId#HGNC:1348 "SAMD9"
* http://www.genenames.org/geneId#HGNC:1349 "SAMD9L"
* http://www.genenames.org/geneId#HGNC:10680 "SDHA"
* http://www.genenames.org/geneId#HGNC:26034 "SDHAF2"
* http://www.genenames.org/geneId#HGNC:10681 "SDHB"
* http://www.genenames.org/geneId#HGNC:10682 "SDHC"
* http://www.genenames.org/geneId#HGNC:10683 "SDHD"
* http://www.genenames.org/geneId#HGNC:23845 "SLX4"
* http://www.genenames.org/geneId#HGNC:6770 "SMAD4"
* http://www.genenames.org/geneId#HGNC:11100 "SMARCA4"
* http://www.genenames.org/geneId#HGNC:11103 "SMARCB1"
* http://www.genenames.org/geneId#HGNC:11119 "SMO"
* http://www.genenames.org/geneId#HGNC:11187 "SOS1"
* http://www.genenames.org/geneId#HGNC:11389 "STK11"
* http://www.genenames.org/geneId#HGNC:16466 "SUFU"
* http://www.genenames.org/geneId#HGNC:11633 "TCF3"
* http://www.genenames.org/geneId#HGNC:11727 "TERC"
* http://www.genenames.org/geneId#HGNC:11730 "TERT"
* http://www.genenames.org/geneId#HGNC:11824 "TINF2"
* http://www.genenames.org/geneId#HGNC:26038 "TMEM127"
* http://www.genenames.org/geneId#HGNC:11998 "TP53"
* http://www.genenames.org/geneId#HGNC:16384 "TRIM28"
* http://www.genenames.org/geneId#HGNC:7523 "TRIM37"
* http://www.genenames.org/geneId#HGNC:12307 "TRIP13"
* http://www.genenames.org/geneId#HGNC:12362 "TSC1"
* http://www.genenames.org/geneId#HGNC:12363 "TSC2"
* http://www.genenames.org/geneId#HGNC:25009 "UBE2T"
* http://www.genenames.org/geneId#HGNC:12687 "VHL"
* http://www.genenames.org/geneId#HGNC:12796 "WT1"
* http://www.genenames.org/geneId#HGNC:12814 "XPA"
* http://www.genenames.org/geneId#HGNC:12816 "XPC"
* http://www.genenames.org/geneId#HGNC:12829 "XRCC2"
